_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 239
batch_size_seasonal_0:
    value: 82
batch_size_seasonal_1:
    value: 225
batch_size_seasonal_2:
    value: 72
batch_size_seasonal_3:
    value: 63
batch_size_trend:
    value: 209
epochs:
    value: 1
learning_rate_resid:
    value: 0.00011619989245963331
learning_rate_seasonal_0:
    value: 2.136796883365021e-06
learning_rate_seasonal_1:
    value: 0.00014192503871737053
learning_rate_seasonal_2:
    value: 1.1341716354670438e-06
learning_rate_seasonal_3:
    value: 1.039512893692502e-05
learning_rate_trend:
    value: 3.2711011872171566e-05
observation_period_resid:
    value: 194
observation_period_seasonal_0:
    value: 169
observation_period_seasonal_1:
    value: 191
observation_period_seasonal_2:
    value: 56
observation_period_seasonal_3:
    value: 130
observation_period_trend:
    value: 182
predict_period_num:
    value: 1
