_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 99
batch_size_seasonal_0:
    value: 151
batch_size_seasonal_1:
    value: 181
batch_size_seasonal_2:
    value: 134
batch_size_seasonal_3:
    value: 31
batch_size_trend:
    value: 99
epochs:
    value: 1
learning_rate_resid:
    value: 8.040992290007876e-05
learning_rate_seasonal_0:
    value: 4.709139210315501e-05
learning_rate_seasonal_1:
    value: 5.537282384586826e-06
learning_rate_seasonal_2:
    value: 0.00027931336144269576
learning_rate_seasonal_3:
    value: 5.476435927230345e-06
learning_rate_trend:
    value: 2.364989980609325e-05
observation_period_resid:
    value: 126
observation_period_seasonal_0:
    value: 215
observation_period_seasonal_1:
    value: 165
observation_period_seasonal_2:
    value: 251
observation_period_seasonal_3:
    value: 75
observation_period_trend:
    value: 87
predict_period_num:
    value: 1
