_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 108
batch_size_seasonal_0:
    value: 110
batch_size_seasonal_1:
    value: 103
batch_size_seasonal_2:
    value: 256
batch_size_seasonal_3:
    value: 241
batch_size_trend:
    value: 125
epochs:
    value: 1
learning_rate_resid:
    value: 0.000219208204947549
learning_rate_seasonal_0:
    value: 1.4211292557678458e-05
learning_rate_seasonal_1:
    value: 8.676742029726333e-05
learning_rate_seasonal_2:
    value: 1.3527593077397527e-05
learning_rate_seasonal_3:
    value: 5.870377078367666e-06
learning_rate_trend:
    value: 1.5516042192262188e-05
observation_period_resid:
    value: 70
observation_period_seasonal_0:
    value: 220
observation_period_seasonal_1:
    value: 61
observation_period_seasonal_2:
    value: 238
observation_period_seasonal_3:
    value: 168
observation_period_trend:
    value: 246
predict_period_num:
    value: 1
