_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 112
batch_size_seasonal_0:
    value: 132
batch_size_seasonal_1:
    value: 91
batch_size_seasonal_2:
    value: 97
batch_size_seasonal_3:
    value: 117
batch_size_trend:
    value: 231
epochs:
    value: 1
learning_rate_resid:
    value: 8.320889949647646e-05
learning_rate_seasonal_0:
    value: 9.233842764273799e-05
learning_rate_seasonal_1:
    value: 0.000101265691144934
learning_rate_seasonal_2:
    value: 8.810184366186577e-05
learning_rate_seasonal_3:
    value: 3.899019225014661e-06
learning_rate_trend:
    value: 5.4296443830651976e-05
observation_period_resid:
    value: 197
observation_period_seasonal_0:
    value: 170
observation_period_seasonal_1:
    value: 176
observation_period_seasonal_2:
    value: 110
observation_period_seasonal_3:
    value: 185
observation_period_trend:
    value: 15
predict_period_num:
    value: 1
