_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 65
batch_size_seasonal_0:
    value: 124
batch_size_seasonal_1:
    value: 134
batch_size_seasonal_2:
    value: 190
batch_size_seasonal_3:
    value: 86
batch_size_trend:
    value: 127
epochs:
    value: 300
learning_rate_resid:
    value: 1.8334408738003524e-05
learning_rate_seasonal_0:
    value: 0.00039940954425028794
learning_rate_seasonal_1:
    value: 0.00042666169647768927
learning_rate_seasonal_2:
    value: 0.00017446831351692845
learning_rate_seasonal_3:
    value: 0.00033251831032581644
learning_rate_trend:
    value: 0.00020029441795952236
observation_period_resid:
    value: 53
observation_period_seasonal_0:
    value: 117
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 26
observation_period_seasonal_3:
    value: 35
observation_period_trend:
    value: 10
predict_period_num:
    value: 1
