_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 146
batch_size_seasonal_0:
    value: 17
batch_size_seasonal_1:
    value: 139
batch_size_seasonal_2:
    value: 131
batch_size_seasonal_3:
    value: 198
batch_size_trend:
    value: 85
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006553502710645765
learning_rate_seasonal_0:
    value: 3.673587816232464e-05
learning_rate_seasonal_1:
    value: 0.0003556300660139575
learning_rate_seasonal_2:
    value: 0.0005994966267025214
learning_rate_seasonal_3:
    value: 8.530779947440688e-05
learning_rate_trend:
    value: 6.003961899388964e-05
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 51
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 39
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
