_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 20
batch_size_seasonal_0:
    value: 124
batch_size_seasonal_1:
    value: 211
batch_size_seasonal_2:
    value: 28
batch_size_seasonal_3:
    value: 23
batch_size_trend:
    value: 237
epochs:
    value: 300
learning_rate_resid:
    value: 0.0001041801855429689
learning_rate_seasonal_0:
    value: 0.00010045968631504395
learning_rate_seasonal_1:
    value: 0.0003899080586656311
learning_rate_seasonal_2:
    value: 0.0006461200811464487
learning_rate_seasonal_3:
    value: 0.0005215479963514043
learning_rate_trend:
    value: 0.0003013278996634321
observation_period_resid:
    value: 8
observation_period_seasonal_0:
    value: 40
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 250
observation_period_seasonal_3:
    value: 9
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
