_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 88
batch_size_seasonal_0:
    value: 116
batch_size_seasonal_1:
    value: 25
batch_size_seasonal_2:
    value: 135
batch_size_seasonal_3:
    value: 119
batch_size_trend:
    value: 42
epochs:
    value: 300
learning_rate_resid:
    value: 0.00020934084212874228
learning_rate_seasonal_0:
    value: 0.0009545753845990329
learning_rate_seasonal_1:
    value: 0.0007573918320032116
learning_rate_seasonal_2:
    value: 0.000625564427498638
learning_rate_seasonal_3:
    value: 0.0009020099926459305
learning_rate_trend:
    value: 0.0004885407036096562
observation_period_resid:
    value: 33
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 13
observation_period_seasonal_2:
    value: 11
observation_period_seasonal_3:
    value: 29
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
