_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 168
batch_size_seasonal:
    value: 35
batch_size_trend:
    value: 139
epochs:
    value: 1
learning_rate_resid:
    value: 0.00039922446251598883
learning_rate_seasonal:
    value: 4.732111711759562e-06
learning_rate_trend:
    value: 0.0002902190224538885
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
