_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 81
batch_size_seasonal_0:
    value: 116
batch_size_seasonal_1:
    value: 136
batch_size_seasonal_2:
    value: 21
batch_size_seasonal_3:
    value: 58
batch_size_trend:
    value: 16
epochs:
    value: 300
learning_rate_resid:
    value: 0.00032830707345255205
learning_rate_seasonal_0:
    value: 0.0001972289459885028
learning_rate_seasonal_1:
    value: 0.00015031019279272868
learning_rate_seasonal_2:
    value: 1.915941240448754e-05
learning_rate_seasonal_3:
    value: 0.00025351991977514245
learning_rate_trend:
    value: 9.472860256449676e-05
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 181
observation_period_seasonal_1:
    value: 145
observation_period_seasonal_2:
    value: 68
observation_period_seasonal_3:
    value: 247
observation_period_trend:
    value: 98
predict_period_num:
    value: 1
