_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 50
batch_size_seasonal_0:
    value: 39
batch_size_seasonal_1:
    value: 31
batch_size_seasonal_2:
    value: 112
batch_size_seasonal_3:
    value: 33
batch_size_trend:
    value: 30
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009519555487206153
learning_rate_seasonal_0:
    value: 3.3497730376660215e-05
learning_rate_seasonal_1:
    value: 0.0006838624503216884
learning_rate_seasonal_2:
    value: 0.0002486904614120312
learning_rate_seasonal_3:
    value: 9.446716545553754e-05
learning_rate_trend:
    value: 0.0005953105169070539
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 16
observation_period_seasonal_2:
    value: 13
observation_period_seasonal_3:
    value: 13
observation_period_trend:
    value: 8
predict_period_num:
    value: 1
