_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 23
batch_size_seasonal_0:
    value: 99
batch_size_seasonal_1:
    value: 92
batch_size_seasonal_2:
    value: 153
batch_size_seasonal_3:
    value: 103
batch_size_trend:
    value: 91
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009171296532336576
learning_rate_seasonal_0:
    value: 0.0003478936498117362
learning_rate_seasonal_1:
    value: 0.000703155254653984
learning_rate_seasonal_2:
    value: 0.0002238292292963187
learning_rate_seasonal_3:
    value: 0.0006805468475422376
learning_rate_trend:
    value: 0.00015232656498093876
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 14
observation_period_seasonal_1:
    value: 8
observation_period_seasonal_2:
    value: 21
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 18
predict_period_num:
    value: 1
