_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 158
batch_size_seasonal_0:
    value: 169
batch_size_seasonal_1:
    value: 47
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 117
batch_size_trend:
    value: 89
epochs:
    value: 300
learning_rate_resid:
    value: 0.00021092434120410967
learning_rate_seasonal_0:
    value: 0.0001648509238731016
learning_rate_seasonal_1:
    value: 0.00010750458884282798
learning_rate_seasonal_2:
    value: 0.0002545436498103557
learning_rate_seasonal_3:
    value: 0.00028411700362331813
learning_rate_trend:
    value: 0.00014611903728488612
observation_period_resid:
    value: 93
observation_period_seasonal_0:
    value: 174
observation_period_seasonal_1:
    value: 30
observation_period_seasonal_2:
    value: 98
observation_period_seasonal_3:
    value: 217
observation_period_trend:
    value: 188
predict_period_num:
    value: 1
