_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 236
batch_size_seasonal:
    value: 96
batch_size_trend:
    value: 87
epochs:
    value: 100
learning_rate_resid:
    value: 9.197694186713096e-05
learning_rate_seasonal:
    value: 0.0006228921757314332
learning_rate_trend:
    value: 0.0001376117620815218
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
