_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 150
batch_size_seasonal_0:
    value: 201
batch_size_seasonal_1:
    value: 220
batch_size_seasonal_2:
    value: 110
batch_size_seasonal_3:
    value: 64
batch_size_trend:
    value: 34
epochs:
    value: 300
learning_rate_resid:
    value: 0.00034058433302648037
learning_rate_seasonal_0:
    value: 0.0007503049398560546
learning_rate_seasonal_1:
    value: 0.0005680149952013268
learning_rate_seasonal_2:
    value: 0.0003461364670810924
learning_rate_seasonal_3:
    value: 0.0002882251271567547
learning_rate_trend:
    value: 0.00018766207829767458
observation_period_resid:
    value: 30
observation_period_seasonal_0:
    value: 10
observation_period_seasonal_1:
    value: 8
observation_period_seasonal_2:
    value: 13
observation_period_seasonal_3:
    value: 10
observation_period_trend:
    value: 108
predict_period_num:
    value: 1
