_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 88
batch_size_seasonal:
    value: 48
batch_size_trend:
    value: 22
epochs:
    value: 1
learning_rate_resid:
    value: 0.00017956424288264396
learning_rate_seasonal:
    value: 0.0007440617500317368
learning_rate_trend:
    value: 7.660583450793696e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
