_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 147
batch_size_seasonal:
    value: 214
batch_size_trend:
    value: 197
epochs:
    value: 1
learning_rate_resid:
    value: 1.453326173525898e-06
learning_rate_seasonal:
    value: 0.00022264687599075897
learning_rate_trend:
    value: 2.7305225019886357e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
