_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 42
batch_size_seasonal_0:
    value: 132
batch_size_seasonal_1:
    value: 62
batch_size_seasonal_2:
    value: 139
batch_size_seasonal_3:
    value: 51
batch_size_trend:
    value: 36
epochs:
    value: 300
learning_rate_resid:
    value: 0.00043450571421121324
learning_rate_seasonal_0:
    value: 0.0005801486146465605
learning_rate_seasonal_1:
    value: 7.828923073636323e-05
learning_rate_seasonal_2:
    value: 0.0009702505495014734
learning_rate_seasonal_3:
    value: 8.164798088119659e-05
learning_rate_trend:
    value: 0.00010181138901250208
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 29
observation_period_seasonal_1:
    value: 42
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 16
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
