wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727944527
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.0008
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
observation_period_num:
  desc: null
  value: 30
predict_period_num:
  desc: null
  value: 1
