_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 195
batch_size_seasonal_0:
    value: 186
batch_size_seasonal_1:
    value: 32
batch_size_seasonal_2:
    value: 252
batch_size_seasonal_3:
    value: 113
batch_size_trend:
    value: 238
epochs:
    value: 1
learning_rate_resid:
    value: 5.3413051226529275e-06
learning_rate_seasonal_0:
    value: 5.039753242953901e-05
learning_rate_seasonal_1:
    value: 2.6159982695729598e-06
learning_rate_seasonal_2:
    value: 0.00016882527389108093
learning_rate_seasonal_3:
    value: 1.2896108350429875e-05
learning_rate_trend:
    value: 2.907045558879455e-06
observation_period_resid:
    value: 209
observation_period_seasonal_0:
    value: 221
observation_period_seasonal_1:
    value: 227
observation_period_seasonal_2:
    value: 232
observation_period_seasonal_3:
    value: 150
observation_period_trend:
    value: 167
predict_period_num:
    value: 1
