_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 107
batch_size_seasonal_0:
    value: 179
batch_size_seasonal_1:
    value: 105
batch_size_seasonal_2:
    value: 231
batch_size_seasonal_3:
    value: 32
batch_size_trend:
    value: 232
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009233538779287182
learning_rate_seasonal_0:
    value: 0.0009792570248455216
learning_rate_seasonal_1:
    value: 0.0009655436260558819
learning_rate_seasonal_2:
    value: 0.0009722044273311763
learning_rate_seasonal_3:
    value: 0.00012186980809171436
learning_rate_trend:
    value: 0.0009840876918124912
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 33
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 33
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
