_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 80
batch_size_seasonal_0:
    value: 47
batch_size_seasonal_1:
    value: 154
batch_size_seasonal_2:
    value: 160
batch_size_seasonal_3:
    value: 162
batch_size_trend:
    value: 31
epochs:
    value: 300
learning_rate_resid:
    value: 0.00046638797923573706
learning_rate_seasonal_0:
    value: 0.00018701567512985115
learning_rate_seasonal_1:
    value: 0.00010241472253908938
learning_rate_seasonal_2:
    value: 0.000674165147135357
learning_rate_seasonal_3:
    value: 0.0008405298478883172
learning_rate_trend:
    value: 4.668291486710994e-05
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 53
observation_period_seasonal_1:
    value: 26
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
