_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 28
batch_size_seasonal_0:
    value: 172
batch_size_seasonal_1:
    value: 53
batch_size_seasonal_2:
    value: 81
batch_size_seasonal_3:
    value: 18
batch_size_trend:
    value: 254
epochs:
    value: 300
learning_rate_resid:
    value: 0.00020640964113191352
learning_rate_seasonal_0:
    value: 0.0006965727363549433
learning_rate_seasonal_1:
    value: 0.000966480027074729
learning_rate_seasonal_2:
    value: 0.00034539161049998825
learning_rate_seasonal_3:
    value: 0.00016242895905399816
learning_rate_trend:
    value: 0.0009674388205993714
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 14
observation_period_seasonal_1:
    value: 9
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
