_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 17
batch_size_seasonal_0:
    value: 191
batch_size_seasonal_1:
    value: 34
batch_size_seasonal_2:
    value: 25
batch_size_seasonal_3:
    value: 166
batch_size_trend:
    value: 103
epochs:
    value: 300
learning_rate_resid:
    value: 4.679274883973453e-05
learning_rate_seasonal_0:
    value: 0.0005761499803517735
learning_rate_seasonal_1:
    value: 0.00018233225386030244
learning_rate_seasonal_2:
    value: 9.554273264522773e-05
learning_rate_seasonal_3:
    value: 0.0006141786446771696
learning_rate_trend:
    value: 8.889722581004415e-05
observation_period_resid:
    value: 8
observation_period_seasonal_0:
    value: 21
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
