_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 64
batch_size_seasonal_0:
    value: 60
batch_size_seasonal_1:
    value: 247
batch_size_seasonal_2:
    value: 113
batch_size_seasonal_3:
    value: 66
batch_size_trend:
    value: 186
epochs:
    value: 200
learning_rate_resid:
    value: 0.000369301719310934
learning_rate_seasonal_0:
    value: 2.832906061809896e-05
learning_rate_seasonal_1:
    value: 1.3520386954066699e-05
learning_rate_seasonal_2:
    value: 4.502374034111121e-05
learning_rate_seasonal_3:
    value: 0.0005935495203493008
learning_rate_trend:
    value: 0.000502491909276176
observation_period_resid:
    value: 96
observation_period_seasonal_0:
    value: 71
observation_period_seasonal_1:
    value: 161
observation_period_seasonal_2:
    value: 45
observation_period_seasonal_3:
    value: 200
observation_period_trend:
    value: 55
predict_period_num:
    value: 1
