_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 228
batch_size_seasonal_0:
    value: 50
batch_size_seasonal_1:
    value: 144
batch_size_seasonal_2:
    value: 101
batch_size_seasonal_3:
    value: 127
batch_size_trend:
    value: 31
epochs:
    value: 300
learning_rate_resid:
    value: 0.0005183100321686116
learning_rate_seasonal_0:
    value: 0.00023693882597308703
learning_rate_seasonal_1:
    value: 0.00041009427658064576
learning_rate_seasonal_2:
    value: 0.0003431980657717307
learning_rate_seasonal_3:
    value: 0.0003518255018147867
learning_rate_trend:
    value: 8.306320187563025e-05
observation_period_resid:
    value: 31
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
