_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 25
batch_size_seasonal_0:
    value: 18
batch_size_seasonal_1:
    value: 90
batch_size_seasonal_2:
    value: 79
batch_size_seasonal_3:
    value: 142
batch_size_trend:
    value: 18
epochs:
    value: 300
learning_rate_resid:
    value: 0.0001305553500106674
learning_rate_seasonal_0:
    value: 0.0004937659633207597
learning_rate_seasonal_1:
    value: 0.00034793358913057557
learning_rate_seasonal_2:
    value: 9.429915472998664e-05
learning_rate_seasonal_3:
    value: 0.00032350753795972554
learning_rate_trend:
    value: 9.836743040381044e-05
observation_period_resid:
    value: 21
observation_period_seasonal_0:
    value: 12
observation_period_seasonal_1:
    value: 13
observation_period_seasonal_2:
    value: 30
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 11
predict_period_num:
    value: 1
