_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 81
batch_size_seasonal_0:
    value: 21
batch_size_seasonal_1:
    value: 151
batch_size_seasonal_2:
    value: 192
batch_size_seasonal_3:
    value: 29
batch_size_trend:
    value: 37
epochs:
    value: 300
learning_rate_resid:
    value: 0.00023909995625234355
learning_rate_seasonal_0:
    value: 0.00021149643429965986
learning_rate_seasonal_1:
    value: 0.0009646210844056339
learning_rate_seasonal_2:
    value: 0.00017704824158251155
learning_rate_seasonal_3:
    value: 2.1129031057999455e-05
learning_rate_trend:
    value: 0.00031820913256764356
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 22
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 25
observation_period_seasonal_3:
    value: 20
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
