_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 44
batch_size_seasonal_0:
    value: 76
batch_size_seasonal_1:
    value: 122
batch_size_seasonal_2:
    value: 41
batch_size_seasonal_3:
    value: 45
batch_size_trend:
    value: 36
epochs:
    value: 300
learning_rate_resid:
    value: 6.129374536809053e-05
learning_rate_seasonal_0:
    value: 0.00019833952909232067
learning_rate_seasonal_1:
    value: 9.288695925078009e-05
learning_rate_seasonal_2:
    value: 0.00022257386220546392
learning_rate_seasonal_3:
    value: 0.00018516222876211605
learning_rate_trend:
    value: 4.382536360015831e-05
observation_period_resid:
    value: 178
observation_period_seasonal_0:
    value: 32
observation_period_seasonal_1:
    value: 61
observation_period_seasonal_2:
    value: 60
observation_period_seasonal_3:
    value: 220
observation_period_trend:
    value: 85
predict_period_num:
    value: 1
