_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 232
batch_size_seasonal:
    value: 89
batch_size_trend:
    value: 45
epochs:
    value: 1
learning_rate_resid:
    value: 0.000842452811846957
learning_rate_seasonal:
    value: 2.6777052204980574e-05
learning_rate_trend:
    value: 0.00010589223406677415
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
