_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 202
batch_size_seasonal_0:
    value: 54
batch_size_seasonal_1:
    value: 115
batch_size_seasonal_2:
    value: 194
batch_size_seasonal_3:
    value: 151
batch_size_trend:
    value: 47
epochs:
    value: 300
learning_rate_resid:
    value: 0.0003137435386535578
learning_rate_seasonal_0:
    value: 0.00024270763828447016
learning_rate_seasonal_1:
    value: 0.0004607768810693857
learning_rate_seasonal_2:
    value: 0.0006464886750268261
learning_rate_seasonal_3:
    value: 0.000798029978449131
learning_rate_trend:
    value: 0.0001807084408550771
observation_period_resid:
    value: 18
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 20
predict_period_num:
    value: 1
