_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 44
batch_size_seasonal_0:
    value: 36
batch_size_seasonal_1:
    value: 177
batch_size_seasonal_2:
    value: 114
batch_size_seasonal_3:
    value: 75
batch_size_trend:
    value: 207
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006669871545122167
learning_rate_seasonal_0:
    value: 0.0006516498651645316
learning_rate_seasonal_1:
    value: 0.0006291957902043911
learning_rate_seasonal_2:
    value: 0.0007622493770942043
learning_rate_seasonal_3:
    value: 0.0009523244689686775
learning_rate_trend:
    value: 0.0007539060750226302
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
