_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 100
batch_size_seasonal_0:
    value: 29
batch_size_seasonal_1:
    value: 35
batch_size_seasonal_2:
    value: 251
batch_size_seasonal_3:
    value: 152
batch_size_trend:
    value: 62
epochs:
    value: 300
learning_rate_resid:
    value: 0.0008924454046804217
learning_rate_seasonal_0:
    value: 0.00033929423154687864
learning_rate_seasonal_1:
    value: 9.70008209197557e-05
learning_rate_seasonal_2:
    value: 0.000506448284899147
learning_rate_seasonal_3:
    value: 0.0007272198878977273
learning_rate_trend:
    value: 0.00023436469191064942
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 9
observation_period_seasonal_2:
    value: 9
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
