_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 248
batch_size_seasonal_0:
    value: 135
batch_size_seasonal_1:
    value: 94
batch_size_seasonal_2:
    value: 150
batch_size_seasonal_3:
    value: 213
batch_size_trend:
    value: 236
epochs:
    value: 1
learning_rate_resid:
    value: 4.755135455380705e-05
learning_rate_seasonal_0:
    value: 5.79018635488639e-05
learning_rate_seasonal_1:
    value: 0.00026126476283345806
learning_rate_seasonal_2:
    value: 0.0006294061504333757
learning_rate_seasonal_3:
    value: 7.430860035429233e-06
learning_rate_trend:
    value: 0.00016666086975752626
observation_period_resid:
    value: 194
observation_period_seasonal_0:
    value: 182
observation_period_seasonal_1:
    value: 126
observation_period_seasonal_2:
    value: 126
observation_period_seasonal_3:
    value: 82
observation_period_trend:
    value: 190
predict_period_num:
    value: 1
