_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 54
batch_size_seasonal_0:
    value: 195
batch_size_seasonal_1:
    value: 74
batch_size_seasonal_2:
    value: 249
batch_size_seasonal_3:
    value: 215
batch_size_trend:
    value: 120
epochs:
    value: 1
learning_rate_resid:
    value: 1.6863898076450089e-06
learning_rate_seasonal_0:
    value: 5.007913045137068e-06
learning_rate_seasonal_1:
    value: 2.0963381391831443e-06
learning_rate_seasonal_2:
    value: 0.0002849095672121969
learning_rate_seasonal_3:
    value: 0.00033809440097854035
learning_rate_trend:
    value: 1.7695956426298442e-06
observation_period_resid:
    value: 14
observation_period_seasonal_0:
    value: 238
observation_period_seasonal_1:
    value: 35
observation_period_seasonal_2:
    value: 9
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 210
predict_period_num:
    value: 1
