_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 97
batch_size_seasonal_0:
    value: 22
batch_size_seasonal_1:
    value: 242
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 27
batch_size_trend:
    value: 139
epochs:
    value: 300
learning_rate_resid:
    value: 6.415484246818471e-05
learning_rate_seasonal_0:
    value: 0.00032316023715777043
learning_rate_seasonal_1:
    value: 2.8972642175597946e-05
learning_rate_seasonal_2:
    value: 5.4131507996476096e-05
learning_rate_seasonal_3:
    value: 1.1331011796027062e-06
learning_rate_trend:
    value: 0.00015993516698016458
observation_period_resid:
    value: 11
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 24
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
