_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 221
batch_size_seasonal_1:
    value: 197
batch_size_seasonal_2:
    value: 191
batch_size_seasonal_3:
    value: 92
batch_size_trend:
    value: 92
epochs:
    value: 300
learning_rate_resid:
    value: 3.6010324688498536e-05
learning_rate_seasonal_0:
    value: 0.0007522031243509124
learning_rate_seasonal_1:
    value: 0.0002387080768878746
learning_rate_seasonal_2:
    value: 0.0006894929422308206
learning_rate_seasonal_3:
    value: 4.297475997116145e-05
learning_rate_trend:
    value: 0.0009757295617322969
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 15
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 68
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
