_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 18
batch_size_seasonal_0:
    value: 21
batch_size_seasonal_1:
    value: 25
batch_size_seasonal_2:
    value: 212
batch_size_seasonal_3:
    value: 198
batch_size_trend:
    value: 116
epochs:
    value: 1
learning_rate_resid:
    value: 1.8847612124133729e-06
learning_rate_seasonal_0:
    value: 1.5008592774149393e-06
learning_rate_seasonal_1:
    value: 1.1357800172124427e-05
learning_rate_seasonal_2:
    value: 0.00048117041939268123
learning_rate_seasonal_3:
    value: 0.00011202890513586023
learning_rate_trend:
    value: 6.302122249600298e-05
observation_period_resid:
    value: 218
observation_period_seasonal_0:
    value: 227
observation_period_seasonal_1:
    value: 102
observation_period_seasonal_2:
    value: 187
observation_period_seasonal_3:
    value: 44
observation_period_trend:
    value: 13
predict_period_num:
    value: 1
