_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 21
batch_size_seasonal_0:
    value: 29
batch_size_seasonal_1:
    value: 128
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 69
batch_size_trend:
    value: 130
epochs:
    value: 300
learning_rate_resid:
    value: 0.00024507610243632564
learning_rate_seasonal_0:
    value: 0.0001530608378949736
learning_rate_seasonal_1:
    value: 0.0006448861412147662
learning_rate_seasonal_2:
    value: 6.95012068121626e-05
learning_rate_seasonal_3:
    value: 0.0002367299444144094
learning_rate_trend:
    value: 0.0003204139231581046
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 30
observation_period_seasonal_1:
    value: 16
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
