_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 126
batch_size_seasonal_0:
    value: 80
batch_size_seasonal_1:
    value: 168
batch_size_seasonal_2:
    value: 44
batch_size_seasonal_3:
    value: 233
batch_size_trend:
    value: 122
epochs:
    value: 1
learning_rate_resid:
    value: 1.655803832603886e-05
learning_rate_seasonal_0:
    value: 4.526656173002098e-05
learning_rate_seasonal_1:
    value: 0.00011791899663961615
learning_rate_seasonal_2:
    value: 0.00034123399410341653
learning_rate_seasonal_3:
    value: 5.211808039375737e-05
learning_rate_trend:
    value: 3.1429287727977756e-05
observation_period_resid:
    value: 179
observation_period_seasonal_0:
    value: 252
observation_period_seasonal_1:
    value: 11
observation_period_seasonal_2:
    value: 196
observation_period_seasonal_3:
    value: 139
observation_period_trend:
    value: 92
predict_period_num:
    value: 1
