_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 128
batch_size_seasonal_0:
    value: 75
batch_size_seasonal_1:
    value: 160
batch_size_seasonal_2:
    value: 150
batch_size_seasonal_3:
    value: 206
batch_size_trend:
    value: 19
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004881474046408
learning_rate_seasonal_0:
    value: 0.00029467494425764156
learning_rate_seasonal_1:
    value: 0.0009972504212748658
learning_rate_seasonal_2:
    value: 0.0007120377614832365
learning_rate_seasonal_3:
    value: 0.0009693574430504561
learning_rate_trend:
    value: 4.735616625640761e-05
observation_period_resid:
    value: 22
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 84
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 23
predict_period_num:
    value: 1
