_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 55
batch_size_seasonal:
    value: 67
batch_size_trend:
    value: 106
epochs:
    value: 1
learning_rate_resid:
    value: 0.00010121201506497115
learning_rate_seasonal:
    value: 0.00039880509677599267
learning_rate_trend:
    value: 1.0029145954481863e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
