_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 98
batch_size_seasonal_0:
    value: 18
batch_size_seasonal_1:
    value: 36
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 44
batch_size_trend:
    value: 94
epochs:
    value: 300
learning_rate_resid:
    value: 0.00013902055071722392
learning_rate_seasonal_0:
    value: 8.245615925140233e-05
learning_rate_seasonal_1:
    value: 0.00016027549988584385
learning_rate_seasonal_2:
    value: 9.617839851595133e-05
learning_rate_seasonal_3:
    value: 0.00022799324653885987
learning_rate_trend:
    value: 0.0002570231311590525
observation_period_resid:
    value: 151
observation_period_seasonal_0:
    value: 170
observation_period_seasonal_1:
    value: 26
observation_period_seasonal_2:
    value: 57
observation_period_seasonal_3:
    value: 106
observation_period_trend:
    value: 179
predict_period_num:
    value: 1
