_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 70
batch_size_seasonal:
    value: 17
batch_size_trend:
    value: 50
epochs:
    value: 1000
learning_rate_resid:
    value: 4.826375118149669e-05
learning_rate_seasonal:
    value: 0.0005809199397484135
learning_rate_trend:
    value: 0.00018697733739906337
observation_period_num:
    value:
        resid: 30
        seasonal: 10
        trend: 30
predict_period_num:
    value: 1
