_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 197
batch_size_seasonal_0:
    value: 25
batch_size_seasonal_1:
    value: 146
batch_size_seasonal_2:
    value: 20
batch_size_seasonal_3:
    value: 47
batch_size_trend:
    value: 118
epochs:
    value: 300
learning_rate_resid:
    value: 0.00040988410476031626
learning_rate_seasonal_0:
    value: 2.2492669107258797e-05
learning_rate_seasonal_1:
    value: 0.00020335232478945983
learning_rate_seasonal_2:
    value: 2.4810551694002915e-05
learning_rate_seasonal_3:
    value: 5.9799780652114716e-05
learning_rate_trend:
    value: 8.806475988691994e-05
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 37
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 52
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 14
predict_period_num:
    value: 1
