_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 114
batch_size_seasonal_0:
    value: 50
batch_size_seasonal_1:
    value: 49
batch_size_seasonal_2:
    value: 87
batch_size_seasonal_3:
    value: 183
batch_size_trend:
    value: 43
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009507398881927832
learning_rate_seasonal_0:
    value: 0.00013960597599711315
learning_rate_seasonal_1:
    value: 0.00013602663839413264
learning_rate_seasonal_2:
    value: 7.127364462454739e-05
learning_rate_seasonal_3:
    value: 0.0004986221893921363
learning_rate_trend:
    value: 0.0003324087009235099
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 18
observation_period_seasonal_1:
    value: 30
observation_period_seasonal_2:
    value: 22
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
