_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 25
batch_size_seasonal_0:
    value: 48
batch_size_seasonal_1:
    value: 158
batch_size_seasonal_2:
    value: 108
batch_size_seasonal_3:
    value: 69
batch_size_trend:
    value: 248
epochs:
    value: 1
learning_rate_resid:
    value: 2.9294902417448076e-06
learning_rate_seasonal_0:
    value: 0.0008118210216576787
learning_rate_seasonal_1:
    value: 1.5291187126488837e-05
learning_rate_seasonal_2:
    value: 4.871047493189776e-05
learning_rate_seasonal_3:
    value: 8.086964502795915e-05
learning_rate_trend:
    value: 0.00014314349987942966
observation_period_resid:
    value: 36
observation_period_seasonal_0:
    value: 239
observation_period_seasonal_1:
    value: 149
observation_period_seasonal_2:
    value: 104
observation_period_seasonal_3:
    value: 173
observation_period_trend:
    value: 48
predict_period_num:
    value: 1
