_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 211
batch_size_seasonal_0:
    value: 180
batch_size_seasonal_1:
    value: 19
batch_size_seasonal_2:
    value: 31
batch_size_seasonal_3:
    value: 116
batch_size_trend:
    value: 59
epochs:
    value: 300
learning_rate_resid:
    value: 0.00036197136259234313
learning_rate_seasonal_0:
    value: 0.00033816019993174694
learning_rate_seasonal_1:
    value: 7.378012325545223e-05
learning_rate_seasonal_2:
    value: 0.00012839717656216377
learning_rate_seasonal_3:
    value: 0.0001347443181048338
learning_rate_trend:
    value: 0.00020188813682337284
observation_period_resid:
    value: 190
observation_period_seasonal_0:
    value: 188
observation_period_seasonal_1:
    value: 20
observation_period_seasonal_2:
    value: 110
observation_period_seasonal_3:
    value: 167
observation_period_trend:
    value: 98
predict_period_num:
    value: 1
