_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 68
batch_size_seasonal_0:
    value: 136
batch_size_seasonal_1:
    value: 89
batch_size_seasonal_2:
    value: 105
batch_size_seasonal_3:
    value: 47
batch_size_trend:
    value: 50
epochs:
    value: 300
learning_rate_resid:
    value: 1.441347256439705e-05
learning_rate_seasonal_0:
    value: 1.5094217624288905e-05
learning_rate_seasonal_1:
    value: 0.00010622633503530496
learning_rate_seasonal_2:
    value: 9.740463811954825e-05
learning_rate_seasonal_3:
    value: 1.913771315618498e-05
learning_rate_trend:
    value: 0.0001287272924708539
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 7
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 21
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
