_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 22
batch_size_seasonal_0:
    value: 27
batch_size_seasonal_1:
    value: 97
batch_size_seasonal_2:
    value: 37
batch_size_seasonal_3:
    value: 204
batch_size_trend:
    value: 40
epochs:
    value: 300
learning_rate_resid:
    value: 0.00015343286780489403
learning_rate_seasonal_0:
    value: 0.0003550424028657619
learning_rate_seasonal_1:
    value: 0.00012363174461713704
learning_rate_seasonal_2:
    value: 0.0006171957612463179
learning_rate_seasonal_3:
    value: 0.00083312569430461
learning_rate_trend:
    value: 0.00021714884423369222
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 42
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 18
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
