_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 49
batch_size_seasonal_0:
    value: 108
batch_size_seasonal_1:
    value: 77
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 111
batch_size_trend:
    value: 34
epochs:
    value: 300
learning_rate_resid:
    value: 0.00011183111229191689
learning_rate_seasonal_0:
    value: 0.000716628072975474
learning_rate_seasonal_1:
    value: 0.0009193782982711474
learning_rate_seasonal_2:
    value: 0.0009363199146312423
learning_rate_seasonal_3:
    value: 0.0004707699420385272
learning_rate_trend:
    value: 0.000259005902421501
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 18
observation_period_seasonal_1:
    value: 15
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 33
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
