_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 217
batch_size_seasonal_0:
    value: 131
batch_size_seasonal_1:
    value: 35
batch_size_seasonal_2:
    value: 86
batch_size_seasonal_3:
    value: 18
batch_size_trend:
    value: 37
epochs:
    value: 1
learning_rate_resid:
    value: 1.8074628304350345e-06
learning_rate_seasonal_0:
    value: 0.00023419710098731194
learning_rate_seasonal_1:
    value: 0.00012870564906002337
learning_rate_seasonal_2:
    value: 2.4228479694494754e-05
learning_rate_seasonal_3:
    value: 1.9975644110033444e-06
learning_rate_trend:
    value: 0.00023371131695733787
observation_period_resid:
    value: 114
observation_period_seasonal_0:
    value: 109
observation_period_seasonal_1:
    value: 172
observation_period_seasonal_2:
    value: 164
observation_period_seasonal_3:
    value: 41
observation_period_trend:
    value: 36
predict_period_num:
    value: 1
