_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 34
batch_size_seasonal_0:
    value: 130
batch_size_seasonal_1:
    value: 83
batch_size_seasonal_2:
    value: 126
batch_size_seasonal_3:
    value: 45
batch_size_trend:
    value: 208
epochs:
    value: 300
learning_rate_resid:
    value: 2.7447075744917615e-05
learning_rate_seasonal_0:
    value: 3.7313425824910584e-05
learning_rate_seasonal_1:
    value: 9.484892329981346e-05
learning_rate_seasonal_2:
    value: 0.00011068984458708256
learning_rate_seasonal_3:
    value: 3.249220421397351e-05
learning_rate_trend:
    value: 0.0003587351966783844
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 23
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
