_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 35
batch_size_seasonal_0:
    value: 88
batch_size_seasonal_1:
    value: 68
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 21
batch_size_trend:
    value: 20
epochs:
    value: 300
learning_rate_resid:
    value: 1.005782759164778e-06
learning_rate_seasonal_0:
    value: 2.8228947944214086e-05
learning_rate_seasonal_1:
    value: 1.990313469188626e-05
learning_rate_seasonal_2:
    value: 2.6191945660530823e-05
learning_rate_seasonal_3:
    value: 4.804717443494775e-05
learning_rate_trend:
    value: 0.00017219631196634813
observation_period_resid:
    value: 11
observation_period_seasonal_0:
    value: 12
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 17
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
