_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 31
batch_size_seasonal_0:
    value: 212
batch_size_seasonal_1:
    value: 69
batch_size_seasonal_2:
    value: 34
batch_size_seasonal_3:
    value: 29
batch_size_trend:
    value: 208
epochs:
    value: 5
learning_rate_resid:
    value: 3.4545984309841e-05
learning_rate_seasonal_0:
    value: 1.2651851830013925e-05
learning_rate_seasonal_1:
    value: 0.00010627785320029054
learning_rate_seasonal_2:
    value: 8.908263874129008e-05
learning_rate_seasonal_3:
    value: 2.668764909137417e-05
learning_rate_trend:
    value: 9.151149889271384e-06
observation_period_resid:
    value: 96
observation_period_seasonal_0:
    value: 13
observation_period_seasonal_1:
    value: 16
observation_period_seasonal_2:
    value: 67
observation_period_seasonal_3:
    value: 252
observation_period_trend:
    value: 58
predict_period_num:
    value: 1
