_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 35
batch_size_seasonal_0:
    value: 28
batch_size_seasonal_1:
    value: 66
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 131
batch_size_trend:
    value: 26
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009207298141960786
learning_rate_seasonal_0:
    value: 0.0001853235005004823
learning_rate_seasonal_1:
    value: 0.00030025334533441444
learning_rate_seasonal_2:
    value: 0.0009774163957408462
learning_rate_seasonal_3:
    value: 0.0006654625268226993
learning_rate_trend:
    value: 5.776884749770517e-05
observation_period_resid:
    value: 10
observation_period_seasonal_0:
    value: 49
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 23
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
