_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 112
batch_size_seasonal_0:
    value: 79
batch_size_seasonal_1:
    value: 24
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 223
batch_size_trend:
    value: 130
epochs:
    value: 300
learning_rate_resid:
    value: 0.0008887268356908011
learning_rate_seasonal_0:
    value: 0.00019855729819191845
learning_rate_seasonal_1:
    value: 0.0008022948731597576
learning_rate_seasonal_2:
    value: 0.0007394913217755428
learning_rate_seasonal_3:
    value: 0.00048664304242939846
learning_rate_trend:
    value: 0.0003957799553701948
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 14
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 36
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 13
predict_period_num:
    value: 1
