_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 164
batch_size_seasonal_0:
    value: 19
batch_size_seasonal_1:
    value: 192
batch_size_seasonal_2:
    value: 117
batch_size_seasonal_3:
    value: 29
batch_size_trend:
    value: 212
epochs:
    value: 1
learning_rate_resid:
    value: 1.452320896312142e-06
learning_rate_seasonal_0:
    value: 5.524384191917722e-06
learning_rate_seasonal_1:
    value: 0.00018050563789830963
learning_rate_seasonal_2:
    value: 0.0007732997743705071
learning_rate_seasonal_3:
    value: 0.0008122108271136922
learning_rate_trend:
    value: 1.978178638569523e-06
observation_period_resid:
    value: 34
observation_period_seasonal_0:
    value: 135
observation_period_seasonal_1:
    value: 81
observation_period_seasonal_2:
    value: 32
observation_period_seasonal_3:
    value: 220
observation_period_trend:
    value: 48
predict_period_num:
    value: 1
