_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 34
batch_size_seasonal_0:
    value: 222
batch_size_seasonal_1:
    value: 187
batch_size_seasonal_2:
    value: 24
batch_size_seasonal_3:
    value: 16
batch_size_trend:
    value: 166
epochs:
    value: 300
learning_rate_resid:
    value: 8.543098257861018e-05
learning_rate_seasonal_0:
    value: 0.0003974905889163145
learning_rate_seasonal_1:
    value: 0.0002505221045064007
learning_rate_seasonal_2:
    value: 4.7662824173442816e-05
learning_rate_seasonal_3:
    value: 0.00017110817008673173
learning_rate_trend:
    value: 0.00013431963840526654
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 30
observation_period_seasonal_2:
    value: 252
observation_period_seasonal_3:
    value: 45
observation_period_trend:
    value: 13
predict_period_num:
    value: 1
