_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 165
batch_size_seasonal_0:
    value: 122
batch_size_seasonal_1:
    value: 17
batch_size_seasonal_2:
    value: 94
batch_size_seasonal_3:
    value: 18
batch_size_trend:
    value: 33
epochs:
    value: 300
learning_rate_resid:
    value: 0.000584695690122956
learning_rate_seasonal_0:
    value: 0.0007938350743920344
learning_rate_seasonal_1:
    value: 5.8654772177333256e-05
learning_rate_seasonal_2:
    value: 0.0006008585134447917
learning_rate_seasonal_3:
    value: 0.00021313735450778504
learning_rate_trend:
    value: 0.0006636125083983942
observation_period_resid:
    value: 19
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 9
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 16
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
