_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 17
batch_size_seasonal_0:
    value: 16
batch_size_seasonal_1:
    value: 229
batch_size_seasonal_2:
    value: 32
batch_size_seasonal_3:
    value: 147
batch_size_trend:
    value: 150
epochs:
    value: 300
learning_rate_resid:
    value: 6.298769229180126e-05
learning_rate_seasonal_0:
    value: 0.0006073684298445799
learning_rate_seasonal_1:
    value: 0.0007417394998563828
learning_rate_seasonal_2:
    value: 0.0009476912444006162
learning_rate_seasonal_3:
    value: 0.0008762650879126588
learning_rate_trend:
    value: 0.0006910777661350586
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 38
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 14
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
