_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 21
batch_size_seasonal_0:
    value: 30
batch_size_seasonal_1:
    value: 61
batch_size_seasonal_2:
    value: 212
batch_size_seasonal_3:
    value: 123
batch_size_trend:
    value: 83
epochs:
    value: 300
learning_rate_resid:
    value: 9.842250568398566e-06
learning_rate_seasonal_0:
    value: 6.544776772204642e-05
learning_rate_seasonal_1:
    value: 4.176353471339515e-05
learning_rate_seasonal_2:
    value: 0.0007536950053643158
learning_rate_seasonal_3:
    value: 1.7603244570286414e-05
learning_rate_trend:
    value: 1.89417747404024e-05
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 10
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 20
observation_period_seasonal_3:
    value: 33
observation_period_trend:
    value: 14
predict_period_num:
    value: 1
