_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 255
batch_size_seasonal_0:
    value: 138
batch_size_seasonal_1:
    value: 44
batch_size_seasonal_2:
    value: 110
batch_size_seasonal_3:
    value: 152
batch_size_trend:
    value: 72
epochs:
    value: 300
learning_rate_resid:
    value: 0.0001641381974189213
learning_rate_seasonal_0:
    value: 0.0003604553074306955
learning_rate_seasonal_1:
    value: 0.00010361117141358826
learning_rate_seasonal_2:
    value: 0.00011843480588275453
learning_rate_seasonal_3:
    value: 9.475902227791612e-05
learning_rate_trend:
    value: 8.863344909546302e-05
observation_period_resid:
    value: 33
observation_period_seasonal_0:
    value: 145
observation_period_seasonal_1:
    value: 111
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 146
observation_period_trend:
    value: 172
predict_period_num:
    value: 1
