_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 190
batch_size_seasonal_0:
    value: 105
batch_size_seasonal_1:
    value: 165
batch_size_seasonal_2:
    value: 18
batch_size_seasonal_3:
    value: 90
batch_size_trend:
    value: 39
epochs:
    value: 300
learning_rate_resid:
    value: 0.00027266558565206483
learning_rate_seasonal_0:
    value: 0.00041093637665892745
learning_rate_seasonal_1:
    value: 0.0004614785229564763
learning_rate_seasonal_2:
    value: 0.00013582259781636994
learning_rate_seasonal_3:
    value: 0.0006642510936570916
learning_rate_trend:
    value: 0.00027065242699770236
observation_period_resid:
    value: 23
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 13
observation_period_seasonal_2:
    value: 14
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
