_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 31
batch_size_seasonal_0:
    value: 44
batch_size_seasonal_1:
    value: 16
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 59
batch_size_trend:
    value: 79
epochs:
    value: 300
learning_rate_resid:
    value: 0.00045338537578103465
learning_rate_seasonal_0:
    value: 0.0001808215033241539
learning_rate_seasonal_1:
    value: 0.00013683396784496107
learning_rate_seasonal_2:
    value: 0.0001247335571497269
learning_rate_seasonal_3:
    value: 9.420465371344981e-05
learning_rate_trend:
    value: 0.0002264010720252406
observation_period_resid:
    value: 18
observation_period_seasonal_0:
    value: 15
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
