_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 160
batch_size_seasonal_0:
    value: 65
batch_size_seasonal_1:
    value: 174
batch_size_seasonal_2:
    value: 178
batch_size_seasonal_3:
    value: 36
batch_size_trend:
    value: 16
epochs:
    value: 300
learning_rate_resid:
    value: 0.0003166290349744031
learning_rate_seasonal_0:
    value: 0.00010828904694852491
learning_rate_seasonal_1:
    value: 0.00011451733459865281
learning_rate_seasonal_2:
    value: 0.00025945020984547996
learning_rate_seasonal_3:
    value: 0.00021117898484721565
learning_rate_trend:
    value: 4.180505174341226e-05
observation_period_resid:
    value: 196
observation_period_seasonal_0:
    value: 174
observation_period_seasonal_1:
    value: 8
observation_period_seasonal_2:
    value: 20
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 133
predict_period_num:
    value: 1
