_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 156
batch_size_seasonal_0:
    value: 121
batch_size_seasonal_1:
    value: 214
batch_size_seasonal_2:
    value: 188
batch_size_seasonal_3:
    value: 159
batch_size_trend:
    value: 115
epochs:
    value: 1
learning_rate_resid:
    value: 1.1325709607340443e-06
learning_rate_seasonal_0:
    value: 3.3209541679559003e-06
learning_rate_seasonal_1:
    value: 5.8158701053205675e-05
learning_rate_seasonal_2:
    value: 2.2938882304655683e-05
learning_rate_seasonal_3:
    value: 1.0817073362544487e-05
learning_rate_trend:
    value: 0.0001611685215881902
observation_period_resid:
    value: 41
observation_period_seasonal_0:
    value: 120
observation_period_seasonal_1:
    value: 119
observation_period_seasonal_2:
    value: 226
observation_period_seasonal_3:
    value: 156
observation_period_trend:
    value: 231
predict_period_num:
    value: 1
