_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 36
batch_size_seasonal_0:
    value: 17
batch_size_seasonal_1:
    value: 163
batch_size_seasonal_2:
    value: 137
batch_size_seasonal_3:
    value: 151
batch_size_trend:
    value: 29
epochs:
    value: 300
learning_rate_resid:
    value: 0.00017389891457605066
learning_rate_seasonal_0:
    value: 8.450499018631672e-05
learning_rate_seasonal_1:
    value: 0.00034930417837490153
learning_rate_seasonal_2:
    value: 0.0002755448625132184
learning_rate_seasonal_3:
    value: 0.0006639530582666196
learning_rate_trend:
    value: 2.037700551585825e-05
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 10
observation_period_seasonal_1:
    value: 48
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
