_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 135
batch_size_seasonal_0:
    value: 222
batch_size_seasonal_1:
    value: 199
batch_size_seasonal_2:
    value: 37
batch_size_seasonal_3:
    value: 241
batch_size_trend:
    value: 52
epochs:
    value: 300
learning_rate_resid:
    value: 0.00013529243732510096
learning_rate_seasonal_0:
    value: 0.0003374384478605072
learning_rate_seasonal_1:
    value: 0.0004018332755047402
learning_rate_seasonal_2:
    value: 0.00018943127353505577
learning_rate_seasonal_3:
    value: 0.0004605197739807708
learning_rate_trend:
    value: 0.0001394235182320582
observation_period_resid:
    value: 189
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 64
observation_period_seasonal_2:
    value: 54
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 242
predict_period_num:
    value: 1
