_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 136
batch_size_seasonal:
    value: 49
batch_size_trend:
    value: 30
epochs:
    value: 1
learning_rate_resid:
    value: 3.4749632888164496e-06
learning_rate_seasonal:
    value: 4.4056098375280733e-05
learning_rate_trend:
    value: 2.4661651289184064e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
