_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 135
batch_size_seasonal_0:
    value: 175
batch_size_seasonal_1:
    value: 204
batch_size_seasonal_2:
    value: 183
batch_size_seasonal_3:
    value: 23
batch_size_trend:
    value: 154
epochs:
    value: 1
learning_rate_resid:
    value: 4.521192765096845e-06
learning_rate_seasonal_0:
    value: 1.40255378608311e-05
learning_rate_seasonal_1:
    value: 6.453558997510911e-06
learning_rate_seasonal_2:
    value: 1.6030876882540628e-06
learning_rate_seasonal_3:
    value: 5.26133684689288e-05
learning_rate_trend:
    value: 0.0001846109893221685
observation_period_resid:
    value: 112
observation_period_seasonal_0:
    value: 149
observation_period_seasonal_1:
    value: 189
observation_period_seasonal_2:
    value: 58
observation_period_seasonal_3:
    value: 152
observation_period_trend:
    value: 139
predict_period_num:
    value: 1
