_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 102
batch_size_seasonal_0:
    value: 151
batch_size_seasonal_1:
    value: 215
batch_size_seasonal_2:
    value: 39
batch_size_seasonal_3:
    value: 28
batch_size_trend:
    value: 169
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006429126970534857
learning_rate_seasonal_0:
    value: 0.000494603421847704
learning_rate_seasonal_1:
    value: 0.0005674414483444585
learning_rate_seasonal_2:
    value: 0.0003012990802565954
learning_rate_seasonal_3:
    value: 0.0001725589922002092
learning_rate_trend:
    value: 0.0006221488770577347
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 44
observation_period_seasonal_1:
    value: 24
observation_period_seasonal_2:
    value: 20
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
