_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 57
batch_size_seasonal:
    value: 20
batch_size_trend:
    value: 24
epochs:
    value: 100
learning_rate_resid:
    value: 9.697690809740112e-05
learning_rate_seasonal:
    value: 0.0008874320555573555
learning_rate_trend:
    value: 0.0006669061302300666
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
