_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 87
batch_size_seasonal:
    value: 174
batch_size_trend:
    value: 240
epochs:
    value: 100
learning_rate_resid:
    value: 1.8961095312687884e-05
learning_rate_seasonal:
    value: 0.00011525450288541428
learning_rate_trend:
    value: 1.2609941079010259e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
