_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 121
batch_size_seasonal_0:
    value: 221
batch_size_seasonal_1:
    value: 56
batch_size_seasonal_2:
    value: 76
batch_size_seasonal_3:
    value: 28
batch_size_trend:
    value: 17
epochs:
    value: 300
learning_rate_resid:
    value: 0.0003979053614182512
learning_rate_seasonal_0:
    value: 0.00037601327197752575
learning_rate_seasonal_1:
    value: 0.0004920066681186387
learning_rate_seasonal_2:
    value: 0.0006379327979549752
learning_rate_seasonal_3:
    value: 0.0001973599645845138
learning_rate_trend:
    value: 0.0006764158865808568
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 68
predict_period_num:
    value: 1
