_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 25
batch_size_seasonal_1:
    value: 155
batch_size_seasonal_2:
    value: 124
batch_size_seasonal_3:
    value: 40
batch_size_trend:
    value: 194
epochs:
    value: 300
learning_rate_resid:
    value: 2.594501027058263e-05
learning_rate_seasonal_0:
    value: 3.485595705147971e-06
learning_rate_seasonal_1:
    value: 0.00012457879164480586
learning_rate_seasonal_2:
    value: 0.00010798017179606207
learning_rate_seasonal_3:
    value: 1.743671472422622e-05
learning_rate_trend:
    value: 0.0009076358317977799
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 184
observation_period_trend:
    value: 28
predict_period_num:
    value: 1
