_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 125
batch_size_seasonal_0:
    value: 121
batch_size_seasonal_1:
    value: 55
batch_size_seasonal_2:
    value: 247
batch_size_seasonal_3:
    value: 169
batch_size_trend:
    value: 82
epochs:
    value: 300
learning_rate_resid:
    value: 5.577912666428857e-05
learning_rate_seasonal_0:
    value: 9.51023635202683e-06
learning_rate_seasonal_1:
    value: 0.0001303452853256295
learning_rate_seasonal_2:
    value: 0.000497139546817353
learning_rate_seasonal_3:
    value: 0.00014991764928175684
learning_rate_trend:
    value: 0.0004242824823721914
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 27
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 18
observation_period_trend:
    value: 78
predict_period_num:
    value: 1
