_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 49
batch_size_seasonal:
    value: 24
batch_size_trend:
    value: 118
epochs:
    value: 1
learning_rate_resid:
    value: 1.8076741566004144e-06
learning_rate_seasonal:
    value: 5.908067281460949e-06
learning_rate_trend:
    value: 1.4853173514170015e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
