_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 188
batch_size_seasonal_0:
    value: 43
batch_size_seasonal_1:
    value: 232
batch_size_seasonal_2:
    value: 168
batch_size_seasonal_3:
    value: 22
batch_size_trend:
    value: 96
epochs:
    value: 300
learning_rate_resid:
    value: 0.0007189150108673919
learning_rate_seasonal_0:
    value: 0.00044837801302468423
learning_rate_seasonal_1:
    value: 0.0005373957503477581
learning_rate_seasonal_2:
    value: 0.00030968857092537557
learning_rate_seasonal_3:
    value: 8.676292231311497e-05
learning_rate_trend:
    value: 0.000643830278682234
observation_period_resid:
    value: 13
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 11
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 49
predict_period_num:
    value: 1
