_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 92
batch_size_seasonal:
    value: 206
batch_size_trend:
    value: 24
epochs:
    value: 1
learning_rate_resid:
    value: 5.639983914947177e-05
learning_rate_seasonal:
    value: 2.8980769837446212e-05
learning_rate_trend:
    value: 0.000220242484918598
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
