_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 79
batch_size_seasonal_0:
    value: 26
batch_size_seasonal_1:
    value: 37
batch_size_seasonal_2:
    value: 204
batch_size_seasonal_3:
    value: 104
batch_size_trend:
    value: 86
epochs:
    value: 300
learning_rate_resid:
    value: 0.00012725159713100268
learning_rate_seasonal_0:
    value: 0.0006192760326421162
learning_rate_seasonal_1:
    value: 0.00033768914031608824
learning_rate_seasonal_2:
    value: 0.0006596441910718066
learning_rate_seasonal_3:
    value: 0.0009627007353084302
learning_rate_trend:
    value: 0.00030058802861210185
observation_period_resid:
    value: 39
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 11
predict_period_num:
    value: 1
