_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 139
batch_size_seasonal_0:
    value: 66
batch_size_seasonal_1:
    value: 185
batch_size_seasonal_2:
    value: 63
batch_size_seasonal_3:
    value: 171
batch_size_trend:
    value: 75
epochs:
    value: 1
learning_rate_resid:
    value: 0.0006575006872395
learning_rate_seasonal_0:
    value: 9.784860959807448e-05
learning_rate_seasonal_1:
    value: 0.0001318241729211272
learning_rate_seasonal_2:
    value: 0.00016913137897739178
learning_rate_seasonal_3:
    value: 0.00010324986539223285
learning_rate_trend:
    value: 1.0261666979993394e-06
observation_period_resid:
    value: 102
observation_period_seasonal_0:
    value: 51
observation_period_seasonal_1:
    value: 111
observation_period_seasonal_2:
    value: 84
observation_period_seasonal_3:
    value: 66
observation_period_trend:
    value: 192
predict_period_num:
    value: 1
