_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 90
batch_size_seasonal_0:
    value: 51
batch_size_seasonal_1:
    value: 16
batch_size_seasonal_2:
    value: 78
batch_size_seasonal_3:
    value: 70
batch_size_trend:
    value: 208
epochs:
    value: 300
learning_rate_resid:
    value: 0.00046948162897285936
learning_rate_seasonal_0:
    value: 0.000135959434255754
learning_rate_seasonal_1:
    value: 0.0009924560735304574
learning_rate_seasonal_2:
    value: 0.000850994919108079
learning_rate_seasonal_3:
    value: 0.00019024976732813316
learning_rate_trend:
    value: 0.0008522692606968093
observation_period_resid:
    value: 20
observation_period_seasonal_0:
    value: 7
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 10
observation_period_seasonal_3:
    value: 13
observation_period_trend:
    value: 26
predict_period_num:
    value: 1
