_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 128
batch_size_seasonal_0:
    value: 24
batch_size_seasonal_1:
    value: 75
batch_size_seasonal_2:
    value: 46
batch_size_seasonal_3:
    value: 50
batch_size_trend:
    value: 197
epochs:
    value: 500
learning_rate_resid:
    value: 0.0007766732022188664
learning_rate_seasonal_0:
    value: 2.383027942061777e-05
learning_rate_seasonal_1:
    value: 0.00011626904101397289
learning_rate_seasonal_2:
    value: 0.0008599253544665889
learning_rate_seasonal_3:
    value: 0.00011007906140572895
learning_rate_trend:
    value: 0.0006703481785402301
observation_period_resid:
    value: 13
observation_period_seasonal_0:
    value: 14
observation_period_seasonal_1:
    value: 10
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
