_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 75
batch_size_seasonal_0:
    value: 206
batch_size_seasonal_1:
    value: 77
batch_size_seasonal_2:
    value: 20
batch_size_seasonal_3:
    value: 178
batch_size_trend:
    value: 41
epochs:
    value: 300
learning_rate_resid:
    value: 6.113974617948114e-05
learning_rate_seasonal_0:
    value: 0.00048737209514102485
learning_rate_seasonal_1:
    value: 0.00016475626674858812
learning_rate_seasonal_2:
    value: 2.0536466288316713e-05
learning_rate_seasonal_3:
    value: 0.00017196722218563954
learning_rate_trend:
    value: 0.00010165307808629653
observation_period_resid:
    value: 194
observation_period_seasonal_0:
    value: 56
observation_period_seasonal_1:
    value: 189
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 194
observation_period_trend:
    value: 200
predict_period_num:
    value: 1
