_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 144
batch_size_seasonal_0:
    value: 147
batch_size_seasonal_1:
    value: 30
batch_size_seasonal_2:
    value: 44
batch_size_seasonal_3:
    value: 70
batch_size_trend:
    value: 217
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006221516554713113
learning_rate_seasonal_0:
    value: 0.0006942538881869897
learning_rate_seasonal_1:
    value: 8.499385829759511e-05
learning_rate_seasonal_2:
    value: 0.00024081927604822638
learning_rate_seasonal_3:
    value: 0.0001731791157046036
learning_rate_trend:
    value: 0.0007281037672022916
observation_period_resid:
    value: 22
observation_period_seasonal_0:
    value: 28
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 32
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
