_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 75
batch_size_seasonal_0:
    value: 44
batch_size_seasonal_1:
    value: 128
batch_size_seasonal_2:
    value: 155
batch_size_seasonal_3:
    value: 132
batch_size_trend:
    value: 77
epochs:
    value: 1
learning_rate_resid:
    value: 0.0002059937574633695
learning_rate_seasonal_0:
    value: 6.05530775499337e-05
learning_rate_seasonal_1:
    value: 1.4297421303325413e-06
learning_rate_seasonal_2:
    value: 4.940252231726212e-06
learning_rate_seasonal_3:
    value: 0.0009561177060157212
learning_rate_trend:
    value: 0.00033524985265372906
observation_period_resid:
    value: 234
observation_period_seasonal_0:
    value: 95
observation_period_seasonal_1:
    value: 127
observation_period_seasonal_2:
    value: 29
observation_period_seasonal_3:
    value: 94
observation_period_trend:
    value: 66
predict_period_num:
    value: 1
