_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 243
batch_size_seasonal_0:
    value: 123
batch_size_seasonal_1:
    value: 122
batch_size_seasonal_2:
    value: 101
batch_size_seasonal_3:
    value: 160
batch_size_trend:
    value: 122
epochs:
    value: 300
learning_rate_resid:
    value: 0.0007705476772050222
learning_rate_seasonal_0:
    value: 0.00046898776456279223
learning_rate_seasonal_1:
    value: 0.00038107447222623193
learning_rate_seasonal_2:
    value: 0.0005832950565023802
learning_rate_seasonal_3:
    value: 0.0006893882527447402
learning_rate_trend:
    value: 0.0007111517033627395
observation_period_resid:
    value: 15
observation_period_seasonal_0:
    value: 23
observation_period_seasonal_1:
    value: 15
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
