_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 125
batch_size_seasonal_1:
    value: 226
batch_size_seasonal_2:
    value: 169
batch_size_seasonal_3:
    value: 64
batch_size_trend:
    value: 125
epochs:
    value: 5
learning_rate_resid:
    value: 0.0003154346460077453
learning_rate_seasonal_0:
    value: 0.0002792513290629619
learning_rate_seasonal_1:
    value: 0.0001799731348007104
learning_rate_seasonal_2:
    value: 4.8772869408199974e-05
learning_rate_seasonal_3:
    value: 7.084074136980957e-05
learning_rate_trend:
    value: 0.00020966568439055082
observation_period_resid:
    value: 63
observation_period_seasonal_0:
    value: 17
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 172
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 80
predict_period_num:
    value: 1
