_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 20
batch_size_seasonal_0:
    value: 220
batch_size_seasonal_1:
    value: 105
batch_size_seasonal_2:
    value: 71
batch_size_seasonal_3:
    value: 182
batch_size_trend:
    value: 32
epochs:
    value: 300
learning_rate_resid:
    value: 0.000608169918442636
learning_rate_seasonal_0:
    value: 0.0008828982363217428
learning_rate_seasonal_1:
    value: 0.0001189008328562521
learning_rate_seasonal_2:
    value: 0.00020173945227506946
learning_rate_seasonal_3:
    value: 0.00073495641954545
learning_rate_trend:
    value: 0.0002690255145462724
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 15
predict_period_num:
    value: 1
