_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 41
batch_size_seasonal_0:
    value: 16
batch_size_seasonal_1:
    value: 43
batch_size_seasonal_2:
    value: 35
batch_size_seasonal_3:
    value: 34
batch_size_trend:
    value: 154
epochs:
    value: 300
learning_rate_resid:
    value: 0.00041495746299204415
learning_rate_seasonal_0:
    value: 0.00012691997695719694
learning_rate_seasonal_1:
    value: 0.00010560738871868106
learning_rate_seasonal_2:
    value: 0.0003308440018437827
learning_rate_seasonal_3:
    value: 0.0001036894475944347
learning_rate_trend:
    value: 0.0006557596125502839
observation_period_resid:
    value: 32
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 25
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
