_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 71
batch_size_seasonal_0:
    value: 175
batch_size_seasonal_1:
    value: 28
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 17
batch_size_trend:
    value: 16
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009818737100685557
learning_rate_seasonal_0:
    value: 0.0007199296523659778
learning_rate_seasonal_1:
    value: 0.000486406153888435
learning_rate_seasonal_2:
    value: 0.00022809492655890073
learning_rate_seasonal_3:
    value: 0.00015049424790659728
learning_rate_trend:
    value: 0.0005689261112441613
observation_period_resid:
    value: 8
observation_period_seasonal_0:
    value: 13
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 19
observation_period_trend:
    value: 11
predict_period_num:
    value: 1
