_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 22
batch_size_seasonal_0:
    value: 66
batch_size_seasonal_1:
    value: 91
batch_size_seasonal_2:
    value: 85
batch_size_seasonal_3:
    value: 130
batch_size_trend:
    value: 34
epochs:
    value: 300
learning_rate_resid:
    value: 0.00011461454332786872
learning_rate_seasonal_0:
    value: 0.0005065208855896543
learning_rate_seasonal_1:
    value: 0.0005554523333265239
learning_rate_seasonal_2:
    value: 0.0002149535490773464
learning_rate_seasonal_3:
    value: 0.0006475033857525854
learning_rate_trend:
    value: 0.00017030802740725277
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 7
observation_period_seasonal_1:
    value: 15
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 21
observation_period_trend:
    value: 10
predict_period_num:
    value: 1
