_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 38
batch_size_seasonal_0:
    value: 26
batch_size_seasonal_1:
    value: 17
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 31
batch_size_trend:
    value: 174
epochs:
    value: 300
learning_rate_resid:
    value: 0.0002417088405426852
learning_rate_seasonal_0:
    value: 0.0005056251732391923
learning_rate_seasonal_1:
    value: 0.00023541136290421226
learning_rate_seasonal_2:
    value: 4.7111530387288834e-05
learning_rate_seasonal_3:
    value: 0.0007690831947589476
learning_rate_trend:
    value: 0.0007035502149094699
observation_period_resid:
    value: 18
observation_period_seasonal_0:
    value: 14
observation_period_seasonal_1:
    value: 15
observation_period_seasonal_2:
    value: 21
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
