_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 172
batch_size_seasonal_0:
    value: 65
batch_size_seasonal_1:
    value: 43
batch_size_seasonal_2:
    value: 145
batch_size_seasonal_3:
    value: 16
batch_size_trend:
    value: 69
epochs:
    value: 300
learning_rate_resid:
    value: 0.00016907613326897983
learning_rate_seasonal_0:
    value: 8.27321775697815e-06
learning_rate_seasonal_1:
    value: 2.0206492772491583e-05
learning_rate_seasonal_2:
    value: 0.00020496325581387964
learning_rate_seasonal_3:
    value: 0.00020120158182884257
learning_rate_trend:
    value: 0.0005819606607873501
observation_period_resid:
    value: 23
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 38
observation_period_seasonal_3:
    value: 10
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
