_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 41
batch_size_seasonal_0:
    value: 165
batch_size_seasonal_1:
    value: 16
batch_size_seasonal_2:
    value: 44
batch_size_seasonal_3:
    value: 46
batch_size_trend:
    value: 26
epochs:
    value: 300
learning_rate_resid:
    value: 0.00011718000342070418
learning_rate_seasonal_0:
    value: 0.0001889104841907421
learning_rate_seasonal_1:
    value: 2.5120900751798626e-05
learning_rate_seasonal_2:
    value: 8.771818578909478e-05
learning_rate_seasonal_3:
    value: 0.00019584153967016805
learning_rate_trend:
    value: 4.57887602022304e-05
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 221
observation_period_seasonal_1:
    value: 51
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 19
observation_period_trend:
    value: 19
predict_period_num:
    value: 1
