_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 202
batch_size_seasonal_0:
    value: 50
batch_size_seasonal_1:
    value: 130
batch_size_seasonal_2:
    value: 50
batch_size_seasonal_3:
    value: 72
batch_size_trend:
    value: 199
epochs:
    value: 300
learning_rate_resid:
    value: 5.696177205540662e-05
learning_rate_seasonal_0:
    value: 0.0005685748003530349
learning_rate_seasonal_1:
    value: 0.0006519925333204811
learning_rate_seasonal_2:
    value: 0.00012030824842205252
learning_rate_seasonal_3:
    value: 0.00016327307235987321
learning_rate_trend:
    value: 0.0006346333559577962
observation_period_resid:
    value: 30
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 9
observation_period_seasonal_2:
    value: 9
observation_period_seasonal_3:
    value: 9
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
