_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 111
batch_size_seasonal:
    value: 29
batch_size_trend:
    value: 51
epochs:
    value: 1
learning_rate_resid:
    value: 1.3294319050613584e-05
learning_rate_seasonal:
    value: 2.711271750833569e-06
learning_rate_trend:
    value: 3.403441125258093e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
