_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 190
batch_size_seasonal_0:
    value: 93
batch_size_seasonal_1:
    value: 95
batch_size_seasonal_2:
    value: 105
batch_size_seasonal_3:
    value: 111
batch_size_trend:
    value: 150
epochs:
    value: 500
learning_rate_resid:
    value: 0.00018513570315316634
learning_rate_seasonal_0:
    value: 0.00024390130450779006
learning_rate_seasonal_1:
    value: 0.0005511502154044901
learning_rate_seasonal_2:
    value: 0.0009539163759807202
learning_rate_seasonal_3:
    value: 0.0007590398057657643
learning_rate_trend:
    value: 0.00044935277184723806
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 35
observation_period_seasonal_1:
    value: 20
observation_period_seasonal_2:
    value: 11
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
