_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 137
batch_size_seasonal_0:
    value: 127
batch_size_seasonal_1:
    value: 71
batch_size_seasonal_2:
    value: 81
batch_size_seasonal_3:
    value: 124
batch_size_trend:
    value: 95
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006678737853552279
learning_rate_seasonal_0:
    value: 0.0002832544601522812
learning_rate_seasonal_1:
    value: 0.00023344724103299152
learning_rate_seasonal_2:
    value: 0.0009481891359050254
learning_rate_seasonal_3:
    value: 0.00024570407872649013
learning_rate_trend:
    value: 0.0005219853339379502
observation_period_resid:
    value: 9
observation_period_seasonal_0:
    value: 31
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
