_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 209
batch_size_seasonal_0:
    value: 249
batch_size_seasonal_1:
    value: 202
batch_size_seasonal_2:
    value: 234
batch_size_seasonal_3:
    value: 173
batch_size_trend:
    value: 165
epochs:
    value: 1
learning_rate_resid:
    value: 0.00013811507331913236
learning_rate_seasonal_0:
    value: 0.00016036440355820522
learning_rate_seasonal_1:
    value: 0.00012732182085404363
learning_rate_seasonal_2:
    value: 1.170226341591906e-06
learning_rate_seasonal_3:
    value: 9.052458142155043e-05
learning_rate_trend:
    value: 1.142802974490001e-06
observation_period_resid:
    value: 103
observation_period_seasonal_0:
    value: 158
observation_period_seasonal_1:
    value: 143
observation_period_seasonal_2:
    value: 246
observation_period_seasonal_3:
    value: 76
observation_period_trend:
    value: 101
predict_period_num:
    value: 1
