_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 251
batch_size_seasonal_0:
    value: 129
batch_size_seasonal_1:
    value: 163
batch_size_seasonal_2:
    value: 235
batch_size_seasonal_3:
    value: 34
batch_size_trend:
    value: 65
epochs:
    value: 1
learning_rate_resid:
    value: 1.2449362655271535e-05
learning_rate_seasonal_0:
    value: 4.343336468066393e-05
learning_rate_seasonal_1:
    value: 0.00026667971109254474
learning_rate_seasonal_2:
    value: 2.490963990657516e-06
learning_rate_seasonal_3:
    value: 0.0004014886706587739
learning_rate_trend:
    value: 3.702707093580336e-05
observation_period_resid:
    value: 122
observation_period_seasonal_0:
    value: 54
observation_period_seasonal_1:
    value: 78
observation_period_seasonal_2:
    value: 194
observation_period_seasonal_3:
    value: 91
observation_period_trend:
    value: 35
predict_period_num:
    value: 1
