_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 38
batch_size_seasonal:
    value: 216
batch_size_trend:
    value: 160
epochs:
    value: 1
learning_rate_resid:
    value: 0.00013466776209320445
learning_rate_seasonal:
    value: 2.999087370902592e-06
learning_rate_trend:
    value: 4.901983770308929e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
