_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 45
batch_size_seasonal_0:
    value: 202
batch_size_seasonal_1:
    value: 249
batch_size_seasonal_2:
    value: 149
batch_size_seasonal_3:
    value: 155
batch_size_trend:
    value: 202
epochs:
    value: 1
learning_rate_resid:
    value: 5.431984975724094e-06
learning_rate_seasonal_0:
    value: 1.1853891673723221e-06
learning_rate_seasonal_1:
    value: 3.787410159642698e-06
learning_rate_seasonal_2:
    value: 1.1684545290661143e-06
learning_rate_seasonal_3:
    value: 4.649810976672179e-05
learning_rate_trend:
    value: 0.0001348713555242008
observation_period_resid:
    value: 11
observation_period_seasonal_0:
    value: 71
observation_period_seasonal_1:
    value: 68
observation_period_seasonal_2:
    value: 208
observation_period_seasonal_3:
    value: 123
observation_period_trend:
    value: 151
predict_period_num:
    value: 1
