_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 42
batch_size_seasonal_0:
    value: 217
batch_size_seasonal_1:
    value: 204
batch_size_seasonal_2:
    value: 102
batch_size_seasonal_3:
    value: 50
batch_size_trend:
    value: 75
epochs:
    value: 300
learning_rate_resid:
    value: 9.981037655905798e-06
learning_rate_seasonal_0:
    value: 0.00027006554845270295
learning_rate_seasonal_1:
    value: 0.00012068648759107733
learning_rate_seasonal_2:
    value: 7.270224616218108e-05
learning_rate_seasonal_3:
    value: 2.6705678124906986e-05
learning_rate_trend:
    value: 0.0006061438854803278
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 23
observation_period_seasonal_2:
    value: 14
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
