_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 46
batch_size_seasonal_0:
    value: 235
batch_size_seasonal_1:
    value: 235
batch_size_seasonal_2:
    value: 104
batch_size_seasonal_3:
    value: 186
batch_size_trend:
    value: 88
epochs:
    value: 1
learning_rate_resid:
    value: 1.8307621625440396e-06
learning_rate_seasonal_0:
    value: 0.00010202986623639238
learning_rate_seasonal_1:
    value: 2.5513837376934693e-06
learning_rate_seasonal_2:
    value: 1.106044101493269e-06
learning_rate_seasonal_3:
    value: 3.390227999452088e-05
learning_rate_trend:
    value: 8.858195598455485e-06
observation_period_resid:
    value: 168
observation_period_seasonal_0:
    value: 130
observation_period_seasonal_1:
    value: 206
observation_period_seasonal_2:
    value: 39
observation_period_seasonal_3:
    value: 241
observation_period_trend:
    value: 245
predict_period_num:
    value: 1
