_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 133
batch_size_seasonal_0:
    value: 56
batch_size_seasonal_1:
    value: 147
batch_size_seasonal_2:
    value: 248
batch_size_seasonal_3:
    value: 94
batch_size_trend:
    value: 73
epochs:
    value: 1
learning_rate_resid:
    value: 4.062293848860351e-05
learning_rate_seasonal_0:
    value: 1.9634657851331103e-05
learning_rate_seasonal_1:
    value: 1.0735527309376534e-05
learning_rate_seasonal_2:
    value: 3.813846089046785e-05
learning_rate_seasonal_3:
    value: 3.0225325663190987e-05
learning_rate_trend:
    value: 7.113500517294756e-05
observation_period_resid:
    value: 224
observation_period_seasonal_0:
    value: 187
observation_period_seasonal_1:
    value: 250
observation_period_seasonal_2:
    value: 211
observation_period_seasonal_3:
    value: 166
observation_period_trend:
    value: 210
predict_period_num:
    value: 1
