_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 81
batch_size_seasonal_0:
    value: 45
batch_size_seasonal_1:
    value: 88
batch_size_seasonal_2:
    value: 188
batch_size_seasonal_3:
    value: 120
batch_size_trend:
    value: 123
epochs:
    value: 300
learning_rate_resid:
    value: 0.000980050418692611
learning_rate_seasonal_0:
    value: 0.0009858622658821053
learning_rate_seasonal_1:
    value: 0.00026984471152186615
learning_rate_seasonal_2:
    value: 0.0006941066410276456
learning_rate_seasonal_3:
    value: 0.0003969604373374693
learning_rate_trend:
    value: 0.0007921628563370255
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 10
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 16
observation_period_trend:
    value: 15
predict_period_num:
    value: 1
