_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 209
batch_size_seasonal_0:
    value: 72
batch_size_seasonal_1:
    value: 115
batch_size_seasonal_2:
    value: 153
batch_size_seasonal_3:
    value: 41
batch_size_trend:
    value: 18
epochs:
    value: 300
learning_rate_resid:
    value: 0.0002112744812763651
learning_rate_seasonal_0:
    value: 3.163573875660143e-05
learning_rate_seasonal_1:
    value: 3.360950277161225e-05
learning_rate_seasonal_2:
    value: 0.0008974841683774046
learning_rate_seasonal_3:
    value: 3.431016732765015e-05
learning_rate_trend:
    value: 5.3394114594916885e-06
observation_period_resid:
    value: 26
observation_period_seasonal_0:
    value: 29
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 10
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
