_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 83
batch_size_seasonal_0:
    value: 39
batch_size_seasonal_1:
    value: 122
batch_size_seasonal_2:
    value: 37
batch_size_seasonal_3:
    value: 64
batch_size_trend:
    value: 37
epochs:
    value: 300
learning_rate_resid:
    value: 0.00029076026456633156
learning_rate_seasonal_0:
    value: 0.00015777252739766184
learning_rate_seasonal_1:
    value: 0.0002131369163969969
learning_rate_seasonal_2:
    value: 9.030285193469562e-05
learning_rate_seasonal_3:
    value: 0.00016375788074059092
learning_rate_trend:
    value: 0.0005788101212791833
observation_period_resid:
    value: 8
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 14
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
