_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 18
batch_size_seasonal_0:
    value: 36
batch_size_seasonal_1:
    value: 71
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 18
batch_size_trend:
    value: 120
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006494252768383254
learning_rate_seasonal_0:
    value: 1.6414211854018804e-05
learning_rate_seasonal_1:
    value: 0.0002744596839625393
learning_rate_seasonal_2:
    value: 1.8751424738545994e-05
learning_rate_seasonal_3:
    value: 0.0009907213109075822
learning_rate_trend:
    value: 0.00016656191651258896
observation_period_resid:
    value: 140
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 25
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
