_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 85
batch_size_seasonal_0:
    value: 256
batch_size_seasonal_1:
    value: 136
batch_size_seasonal_2:
    value: 32
batch_size_seasonal_3:
    value: 71
batch_size_trend:
    value: 46
epochs:
    value: 1
learning_rate_resid:
    value: 0.000386779805609803
learning_rate_seasonal_0:
    value: 2.583725406031903e-05
learning_rate_seasonal_1:
    value: 0.000939950756105295
learning_rate_seasonal_2:
    value: 8.206110271181416e-05
learning_rate_seasonal_3:
    value: 1.741299599929861e-05
learning_rate_trend:
    value: 1.4725369806209567e-06
observation_period_resid:
    value: 248
observation_period_seasonal_0:
    value: 91
observation_period_seasonal_1:
    value: 138
observation_period_seasonal_2:
    value: 218
observation_period_seasonal_3:
    value: 107
observation_period_trend:
    value: 132
predict_period_num:
    value: 1
