_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 29
batch_size_seasonal_0:
    value: 116
batch_size_seasonal_1:
    value: 146
batch_size_seasonal_2:
    value: 212
batch_size_seasonal_3:
    value: 100
batch_size_trend:
    value: 246
epochs:
    value: 300
learning_rate_resid:
    value: 0.0007430373211506457
learning_rate_seasonal_0:
    value: 0.00015207790051888234
learning_rate_seasonal_1:
    value: 0.00023704434949700998
learning_rate_seasonal_2:
    value: 0.0009796067374673687
learning_rate_seasonal_3:
    value: 0.000322376432011282
learning_rate_trend:
    value: 0.0008087096633273017
observation_period_resid:
    value: 15
observation_period_seasonal_0:
    value: 34
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
