_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 75
batch_size_seasonal_0:
    value: 190
batch_size_seasonal_1:
    value: 65
batch_size_seasonal_2:
    value: 25
batch_size_seasonal_3:
    value: 34
batch_size_trend:
    value: 127
epochs:
    value: 300
learning_rate_resid:
    value: 0.00018637360517349675
learning_rate_seasonal_0:
    value: 0.0005627244660875208
learning_rate_seasonal_1:
    value: 0.00024608070100553175
learning_rate_seasonal_2:
    value: 0.0006794215868785664
learning_rate_seasonal_3:
    value: 0.00019593562920564657
learning_rate_trend:
    value: 0.0009595027289612512
observation_period_resid:
    value: 18
observation_period_seasonal_0:
    value: 21
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 7
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
