_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 25
batch_size_seasonal_0:
    value: 176
batch_size_seasonal_1:
    value: 49
batch_size_seasonal_2:
    value: 43
batch_size_seasonal_3:
    value: 32
batch_size_trend:
    value: 117
epochs:
    value: 300
learning_rate_resid:
    value: 0.00024540982199409457
learning_rate_seasonal_0:
    value: 0.0009829680015515229
learning_rate_seasonal_1:
    value: 0.0002516604891985603
learning_rate_seasonal_2:
    value: 0.0007572699505938255
learning_rate_seasonal_3:
    value: 0.0001621572890432808
learning_rate_trend:
    value: 0.00020070953992015278
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 22
observation_period_seasonal_1:
    value: 13
observation_period_seasonal_2:
    value: 17
observation_period_seasonal_3:
    value: 19
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
