_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 24
batch_size_seasonal_0:
    value: 47
batch_size_seasonal_1:
    value: 52
batch_size_seasonal_2:
    value: 244
batch_size_seasonal_3:
    value: 78
batch_size_trend:
    value: 196
epochs:
    value: 300
learning_rate_resid:
    value: 7.103499801503369e-05
learning_rate_seasonal_0:
    value: 9.590390879565091e-05
learning_rate_seasonal_1:
    value: 0.0002075764683800737
learning_rate_seasonal_2:
    value: 0.0005793586752285613
learning_rate_seasonal_3:
    value: 0.0002685545654932206
learning_rate_trend:
    value: 0.00024289207162824682
observation_period_resid:
    value: 48
observation_period_seasonal_0:
    value: 151
observation_period_seasonal_1:
    value: 77
observation_period_seasonal_2:
    value: 132
observation_period_seasonal_3:
    value: 169
observation_period_trend:
    value: 55
predict_period_num:
    value: 1
