_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 231
batch_size_seasonal_0:
    value: 171
batch_size_seasonal_1:
    value: 226
batch_size_seasonal_2:
    value: 23
batch_size_seasonal_3:
    value: 96
batch_size_trend:
    value: 166
epochs:
    value: 1
learning_rate_resid:
    value: 2.3575488710680293e-05
learning_rate_seasonal_0:
    value: 3.990950551041235e-05
learning_rate_seasonal_1:
    value: 3.6683497955473785e-06
learning_rate_seasonal_2:
    value: 0.0005986182967392702
learning_rate_seasonal_3:
    value: 5.642814924116213e-05
learning_rate_trend:
    value: 2.799394450408178e-05
observation_period_resid:
    value: 80
observation_period_seasonal_0:
    value: 92
observation_period_seasonal_1:
    value: 65
observation_period_seasonal_2:
    value: 161
observation_period_seasonal_3:
    value: 136
observation_period_trend:
    value: 154
predict_period_num:
    value: 1
