_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 168
batch_size_seasonal_0:
    value: 90
batch_size_seasonal_1:
    value: 120
batch_size_seasonal_2:
    value: 63
batch_size_seasonal_3:
    value: 103
batch_size_trend:
    value: 17
epochs:
    value: 300
learning_rate_resid:
    value: 0.0005821071483316139
learning_rate_seasonal_0:
    value: 0.000641763897711025
learning_rate_seasonal_1:
    value: 0.0006149944215370888
learning_rate_seasonal_2:
    value: 0.00032732087233840765
learning_rate_seasonal_3:
    value: 0.0003945828479062341
learning_rate_trend:
    value: 0.00022729458521905302
observation_period_resid:
    value: 21
observation_period_seasonal_0:
    value: 15
observation_period_seasonal_1:
    value: 20
observation_period_seasonal_2:
    value: 18
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
