_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 202
batch_size_seasonal_0:
    value: 138
batch_size_seasonal_1:
    value: 162
batch_size_seasonal_2:
    value: 217
batch_size_seasonal_3:
    value: 62
batch_size_trend:
    value: 142
epochs:
    value: 1
learning_rate_resid:
    value: 0.000251055436720502
learning_rate_seasonal_0:
    value: 0.00013666310838846859
learning_rate_seasonal_1:
    value: 0.0006317461708664388
learning_rate_seasonal_2:
    value: 1.1259845418662665e-05
learning_rate_seasonal_3:
    value: 1.3387624464539187e-05
learning_rate_trend:
    value: 6.857150934549593e-05
observation_period_resid:
    value: 124
observation_period_seasonal_0:
    value: 140
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 82
observation_period_trend:
    value: 183
predict_period_num:
    value: 1
