_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 122
batch_size_seasonal_0:
    value: 117
batch_size_seasonal_1:
    value: 42
batch_size_seasonal_2:
    value: 140
batch_size_seasonal_3:
    value: 28
batch_size_trend:
    value: 84
epochs:
    value: 300
learning_rate_resid:
    value: 0.0005717771653074142
learning_rate_seasonal_0:
    value: 0.0005217407621398729
learning_rate_seasonal_1:
    value: 0.0007176526017094414
learning_rate_seasonal_2:
    value: 0.0009955194884617193
learning_rate_seasonal_3:
    value: 0.00030616573778462805
learning_rate_trend:
    value: 0.00021076009161061788
observation_period_resid:
    value: 13
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 9
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
