_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 187
batch_size_seasonal_0:
    value: 174
batch_size_seasonal_1:
    value: 63
batch_size_seasonal_2:
    value: 47
batch_size_seasonal_3:
    value: 18
batch_size_trend:
    value: 127
epochs:
    value: 300
learning_rate_resid:
    value: 0.00024448875517737854
learning_rate_seasonal_0:
    value: 0.00013578587770864508
learning_rate_seasonal_1:
    value: 4.369295299451781e-05
learning_rate_seasonal_2:
    value: 7.039412496932759e-05
learning_rate_seasonal_3:
    value: 0.00036938987044359006
learning_rate_trend:
    value: 0.00010682109215432726
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 9
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 21
predict_period_num:
    value: 1
