_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 63
batch_size_seasonal_0:
    value: 27
batch_size_seasonal_1:
    value: 193
batch_size_seasonal_2:
    value: 256
batch_size_seasonal_3:
    value: 198
batch_size_trend:
    value: 229
epochs:
    value: 300
learning_rate_resid:
    value: 4.2309139631617654e-05
learning_rate_seasonal_0:
    value: 7.88099611941642e-05
learning_rate_seasonal_1:
    value: 3.023212087541594e-05
learning_rate_seasonal_2:
    value: 0.00014048446779042743
learning_rate_seasonal_3:
    value: 4.5637397619110445e-05
learning_rate_trend:
    value: 0.0009598979144146301
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 16
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 29
observation_period_seasonal_3:
    value: 13
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
