_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 121
batch_size_seasonal:
    value: 207
batch_size_trend:
    value: 73
epochs:
    value: 100
learning_rate_resid:
    value: 9.840501838057743e-06
learning_rate_seasonal:
    value: 0.00011101139725892515
learning_rate_trend:
    value: 1.1087833674317428e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
