_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 137
batch_size_seasonal:
    value: 16
batch_size_trend:
    value: 228
epochs:
    value: 100
learning_rate_resid:
    value: 3.129965472999596e-05
learning_rate_seasonal:
    value: 0.00036182172825156313
learning_rate_trend:
    value: 1.7739726588170999e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
