_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 25
batch_size_seasonal_0:
    value: 150
batch_size_seasonal_1:
    value: 150
batch_size_seasonal_2:
    value: 71
batch_size_seasonal_3:
    value: 114
batch_size_trend:
    value: 18
epochs:
    value: 1
learning_rate_resid:
    value: 7.960034787688269e-05
learning_rate_seasonal_0:
    value: 1.477511178084069e-05
learning_rate_seasonal_1:
    value: 0.0002853304835929357
learning_rate_seasonal_2:
    value: 0.00021715187683430537
learning_rate_seasonal_3:
    value: 0.00018878839602053346
learning_rate_trend:
    value: 1.4976902240995215e-05
observation_period_resid:
    value: 201
observation_period_seasonal_0:
    value: 26
observation_period_seasonal_1:
    value: 236
observation_period_seasonal_2:
    value: 160
observation_period_seasonal_3:
    value: 49
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
