_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 113
batch_size_seasonal_0:
    value: 137
batch_size_seasonal_1:
    value: 25
batch_size_seasonal_2:
    value: 251
batch_size_seasonal_3:
    value: 148
batch_size_trend:
    value: 60
epochs:
    value: 1
learning_rate_resid:
    value: 9.12193927658065e-06
learning_rate_seasonal_0:
    value: 1.425623260626277e-06
learning_rate_seasonal_1:
    value: 3.0350953160892295e-05
learning_rate_seasonal_2:
    value: 0.00022581886394672975
learning_rate_seasonal_3:
    value: 0.0005218037082316177
learning_rate_trend:
    value: 0.0003324865844364849
observation_period_resid:
    value: 113
observation_period_seasonal_0:
    value: 81
observation_period_seasonal_1:
    value: 144
observation_period_seasonal_2:
    value: 120
observation_period_seasonal_3:
    value: 237
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
