_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 171
batch_size_seasonal_0:
    value: 183
batch_size_seasonal_1:
    value: 45
batch_size_seasonal_2:
    value: 199
batch_size_seasonal_3:
    value: 233
batch_size_trend:
    value: 166
epochs:
    value: 1
learning_rate_resid:
    value: 3.209271405682977e-06
learning_rate_seasonal_0:
    value: 0.0003694478343494853
learning_rate_seasonal_1:
    value: 1.1687463096883237e-05
learning_rate_seasonal_2:
    value: 1.1722369793092572e-06
learning_rate_seasonal_3:
    value: 1.258101439376411e-05
learning_rate_trend:
    value: 3.7941074073528435e-06
observation_period_resid:
    value: 151
observation_period_seasonal_0:
    value: 59
observation_period_seasonal_1:
    value: 236
observation_period_seasonal_2:
    value: 63
observation_period_seasonal_3:
    value: 195
observation_period_trend:
    value: 214
predict_period_num:
    value: 1
