_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 64
batch_size_seasonal_1:
    value: 103
batch_size_seasonal_2:
    value: 227
batch_size_seasonal_3:
    value: 60
batch_size_trend:
    value: 95
epochs:
    value: 300
learning_rate_resid:
    value: 7.03924902616613e-05
learning_rate_seasonal_0:
    value: 0.0005670250489359773
learning_rate_seasonal_1:
    value: 0.0006151717938397003
learning_rate_seasonal_2:
    value: 0.0006307175783347395
learning_rate_seasonal_3:
    value: 0.0009093786272155121
learning_rate_trend:
    value: 0.0008605679610728868
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 7
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 16
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 8
predict_period_num:
    value: 1
