_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 124
batch_size_seasonal_0:
    value: 116
batch_size_seasonal_1:
    value: 254
batch_size_seasonal_2:
    value: 85
batch_size_seasonal_3:
    value: 123
batch_size_trend:
    value: 45
epochs:
    value: 300
learning_rate_resid:
    value: 0.0001882470216234829
learning_rate_seasonal_0:
    value: 0.0006828972698269891
learning_rate_seasonal_1:
    value: 0.000674404552077101
learning_rate_seasonal_2:
    value: 6.491009699002938e-05
learning_rate_seasonal_3:
    value: 8.825352304488835e-05
learning_rate_trend:
    value: 0.0006642964513775525
observation_period_resid:
    value: 20
observation_period_seasonal_0:
    value: 7
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 17
observation_period_seasonal_3:
    value: 20
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
