_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 16
batch_size_seasonal_1:
    value: 57
batch_size_seasonal_2:
    value: 124
batch_size_seasonal_3:
    value: 92
batch_size_trend:
    value: 140
epochs:
    value: 300
learning_rate_resid:
    value: 6.373835854834866e-05
learning_rate_seasonal_0:
    value: 7.005241597981609e-05
learning_rate_seasonal_1:
    value: 0.0006339623822353624
learning_rate_seasonal_2:
    value: 0.0005135303882600146
learning_rate_seasonal_3:
    value: 0.000588946841599191
learning_rate_trend:
    value: 0.00018337655424356704
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 31
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 36
predict_period_num:
    value: 1
