_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 179
batch_size_seasonal_0:
    value: 34
batch_size_seasonal_1:
    value: 158
batch_size_seasonal_2:
    value: 20
batch_size_seasonal_3:
    value: 101
batch_size_trend:
    value: 27
epochs:
    value: 300
learning_rate_resid:
    value: 0.0007234273774435494
learning_rate_seasonal_0:
    value: 0.0001038739535399735
learning_rate_seasonal_1:
    value: 0.00020205995157404424
learning_rate_seasonal_2:
    value: 5.192011337583312e-05
learning_rate_seasonal_3:
    value: 0.000960176488606088
learning_rate_trend:
    value: 6.282516697543941e-05
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 11
observation_period_seasonal_1:
    value: 29
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 8
predict_period_num:
    value: 1
