_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 87
batch_size_seasonal_0:
    value: 210
batch_size_seasonal_1:
    value: 74
batch_size_seasonal_2:
    value: 26
batch_size_seasonal_3:
    value: 212
batch_size_trend:
    value: 218
epochs:
    value: 5
learning_rate_resid:
    value: 0.0007859261359451847
learning_rate_seasonal_0:
    value: 0.000341689283125055
learning_rate_seasonal_1:
    value: 0.0005968731781387973
learning_rate_seasonal_2:
    value: 3.4417441254428456e-05
learning_rate_seasonal_3:
    value: 0.0006560619729077071
learning_rate_trend:
    value: 0.0004197386527463125
observation_period_resid:
    value: 21
observation_period_seasonal_0:
    value: 17
observation_period_seasonal_1:
    value: 11
observation_period_seasonal_2:
    value: 12
observation_period_seasonal_3:
    value: 16
observation_period_trend:
    value: 12
predict_period_num:
    value: 1
