_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 106
batch_size_seasonal_0:
    value: 29
batch_size_seasonal_1:
    value: 43
batch_size_seasonal_2:
    value: 132
batch_size_seasonal_3:
    value: 78
batch_size_trend:
    value: 82
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009616859319551283
learning_rate_seasonal_0:
    value: 0.0002611511446315947
learning_rate_seasonal_1:
    value: 0.0006222650001541163
learning_rate_seasonal_2:
    value: 0.0004388346776949093
learning_rate_seasonal_3:
    value: 0.0002489861450357806
learning_rate_trend:
    value: 0.00020995956511775144
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 22
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 19
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
