_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 67
batch_size_seasonal_0:
    value: 149
batch_size_seasonal_1:
    value: 235
batch_size_seasonal_2:
    value: 167
batch_size_seasonal_3:
    value: 226
batch_size_trend:
    value: 100
epochs:
    value: 1
learning_rate_resid:
    value: 1.8011760700575976e-06
learning_rate_seasonal_0:
    value: 0.00019451928588341984
learning_rate_seasonal_1:
    value: 2.895431703208313e-06
learning_rate_seasonal_2:
    value: 0.0001267087696688874
learning_rate_seasonal_3:
    value: 0.0007029350300404411
learning_rate_trend:
    value: 0.0009721994096928466
observation_period_resid:
    value: 12
observation_period_seasonal_0:
    value: 95
observation_period_seasonal_1:
    value: 74
observation_period_seasonal_2:
    value: 180
observation_period_seasonal_3:
    value: 132
observation_period_trend:
    value: 212
predict_period_num:
    value: 1
