_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 151
batch_size_seasonal_0:
    value: 27
batch_size_seasonal_1:
    value: 46
batch_size_seasonal_2:
    value: 35
batch_size_seasonal_3:
    value: 19
batch_size_trend:
    value: 16
epochs:
    value: 300
learning_rate_resid:
    value: 0.0002646308826891474
learning_rate_seasonal_0:
    value: 0.0002644847116314593
learning_rate_seasonal_1:
    value: 0.0005785192857039385
learning_rate_seasonal_2:
    value: 2.6986725893176912e-05
learning_rate_seasonal_3:
    value: 0.0009201202878626857
learning_rate_trend:
    value: 9.007966235471077e-05
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
