_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 43
batch_size_seasonal_0:
    value: 54
batch_size_seasonal_1:
    value: 116
batch_size_seasonal_2:
    value: 31
batch_size_seasonal_3:
    value: 151
batch_size_trend:
    value: 17
epochs:
    value: 300
learning_rate_resid:
    value: 0.00042986678296899443
learning_rate_seasonal_0:
    value: 0.0009865596345313245
learning_rate_seasonal_1:
    value: 0.0001484242418827821
learning_rate_seasonal_2:
    value: 8.411452895580493e-05
learning_rate_seasonal_3:
    value: 0.0005369785453693631
learning_rate_trend:
    value: 3.8196610118856964e-05
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 18
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
