_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 145
batch_size_seasonal_0:
    value: 146
batch_size_seasonal_1:
    value: 60
batch_size_seasonal_2:
    value: 44
batch_size_seasonal_3:
    value: 30
batch_size_trend:
    value: 49
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006329125308394092
learning_rate_seasonal_0:
    value: 0.0009883213953294518
learning_rate_seasonal_1:
    value: 4.079393098551156e-05
learning_rate_seasonal_2:
    value: 0.0001857005882815361
learning_rate_seasonal_3:
    value: 0.0007074389761846369
learning_rate_trend:
    value: 0.0003950632010224091
observation_period_resid:
    value: 16
observation_period_seasonal_0:
    value: 9
observation_period_seasonal_1:
    value: 8
observation_period_seasonal_2:
    value: 18
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
