_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 124
batch_size_seasonal_0:
    value: 20
batch_size_seasonal_1:
    value: 188
batch_size_seasonal_2:
    value: 195
batch_size_seasonal_3:
    value: 95
batch_size_trend:
    value: 32
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004611532152884647
learning_rate_seasonal_0:
    value: 0.00010940143305559868
learning_rate_seasonal_1:
    value: 0.00023678808870649713
learning_rate_seasonal_2:
    value: 0.0002894095104319927
learning_rate_seasonal_3:
    value: 0.0002936601291895537
learning_rate_trend:
    value: 2.2340226588341073e-05
observation_period_resid:
    value: 58
observation_period_seasonal_0:
    value: 177
observation_period_seasonal_1:
    value: 11
observation_period_seasonal_2:
    value: 69
observation_period_seasonal_3:
    value: 209
observation_period_trend:
    value: 27
predict_period_num:
    value: 1
