_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 32
batch_size_seasonal_0:
    value: 19
batch_size_seasonal_1:
    value: 34
batch_size_seasonal_2:
    value: 20
batch_size_seasonal_3:
    value: 120
batch_size_trend:
    value: 232
epochs:
    value: 300
learning_rate_resid:
    value: 6.577677867567627e-05
learning_rate_seasonal_0:
    value: 0.00014018728210616471
learning_rate_seasonal_1:
    value: 0.00012137513841261055
learning_rate_seasonal_2:
    value: 0.0002359805738088743
learning_rate_seasonal_3:
    value: 0.0003584428495512724
learning_rate_trend:
    value: 0.00024035196656608756
observation_period_resid:
    value: 97
observation_period_seasonal_0:
    value: 122
observation_period_seasonal_1:
    value: 101
observation_period_seasonal_2:
    value: 148
observation_period_seasonal_3:
    value: 252
observation_period_trend:
    value: 134
predict_period_num:
    value: 1
