_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 154
batch_size_seasonal:
    value: 256
batch_size_trend:
    value: 75
epochs:
    value: 1000
learning_rate_resid:
    value: 0.0005123939495236025
learning_rate_seasonal:
    value: 6.355740458281686e-05
learning_rate_trend:
    value: 7.276337541332485e-05
observation_period_num:
    value: 192
predict_period_num:
    value: 1
