_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 54
batch_size_seasonal_0:
    value: 103
batch_size_seasonal_1:
    value: 144
batch_size_seasonal_2:
    value: 22
batch_size_seasonal_3:
    value: 146
batch_size_trend:
    value: 57
epochs:
    value: 300
learning_rate_resid:
    value: 7.495406113413543e-05
learning_rate_seasonal_0:
    value: 0.0008922522208266279
learning_rate_seasonal_1:
    value: 0.0005564063623388238
learning_rate_seasonal_2:
    value: 0.00012671990215831424
learning_rate_seasonal_3:
    value: 0.00020082888946698732
learning_rate_trend:
    value: 6.708154129662126e-05
observation_period_resid:
    value: 12
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 18
observation_period_seasonal_3:
    value: 90
observation_period_trend:
    value: 9
predict_period_num:
    value: 1
