_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 68
batch_size_seasonal_0:
    value: 151
batch_size_seasonal_1:
    value: 18
batch_size_seasonal_2:
    value: 28
batch_size_seasonal_3:
    value: 80
batch_size_trend:
    value: 31
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004020002553249557
learning_rate_seasonal_0:
    value: 0.0008308199014111168
learning_rate_seasonal_1:
    value: 0.00017786620380025816
learning_rate_seasonal_2:
    value: 0.0007033093239394565
learning_rate_seasonal_3:
    value: 0.000761201312494682
learning_rate_trend:
    value: 0.00022184423320473115
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 9
observation_period_seasonal_1:
    value: 22
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 5
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
