_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 234
batch_size_seasonal_0:
    value: 16
batch_size_seasonal_1:
    value: 248
batch_size_seasonal_2:
    value: 50
batch_size_seasonal_3:
    value: 142
batch_size_trend:
    value: 48
epochs:
    value: 300
learning_rate_resid:
    value: 0.00021346384760085146
learning_rate_seasonal_0:
    value: 0.00012043003084372219
learning_rate_seasonal_1:
    value: 0.00033681638647322054
learning_rate_seasonal_2:
    value: 0.00013051584474052695
learning_rate_seasonal_3:
    value: 0.00020938713513469332
learning_rate_trend:
    value: 4.66069714817907e-05
observation_period_resid:
    value: 78
observation_period_seasonal_0:
    value: 185
observation_period_seasonal_1:
    value: 27
observation_period_seasonal_2:
    value: 134
observation_period_seasonal_3:
    value: 163
observation_period_trend:
    value: 85
predict_period_num:
    value: 1
