_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 53
                - 55
            "2":
                - 1
                - 35
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 217
batch_size_seasonal:
    value: 87
batch_size_trend:
    value: 219
epochs:
    value: 1
learning_rate_resid:
    value: 5.575141828394219e-06
learning_rate_seasonal:
    value: 2.3634595892832387e-06
learning_rate_trend:
    value: 1.0373118040775958e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
