_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 18
batch_size_seasonal_0:
    value: 236
batch_size_seasonal_1:
    value: 29
batch_size_seasonal_2:
    value: 58
batch_size_seasonal_3:
    value: 17
batch_size_trend:
    value: 216
epochs:
    value: 300
learning_rate_resid:
    value: 5.6803480664591135e-05
learning_rate_seasonal_0:
    value: 0.0002796328748352246
learning_rate_seasonal_1:
    value: 5.4605206002228943e-05
learning_rate_seasonal_2:
    value: 0.00013483099593761814
learning_rate_seasonal_3:
    value: 6.973472474047547e-05
learning_rate_trend:
    value: 0.0003981821204048228
observation_period_resid:
    value: 170
observation_period_seasonal_0:
    value: 215
observation_period_seasonal_1:
    value: 29
observation_period_seasonal_2:
    value: 160
observation_period_seasonal_3:
    value: 95
observation_period_trend:
    value: 219
predict_period_num:
    value: 1
