_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 80
batch_size_seasonal_0:
    value: 24
batch_size_seasonal_1:
    value: 141
batch_size_seasonal_2:
    value: 108
batch_size_seasonal_3:
    value: 179
batch_size_trend:
    value: 58
epochs:
    value: 300
learning_rate_resid:
    value: 0.00045457222652129585
learning_rate_seasonal_0:
    value: 0.00016457774355828589
learning_rate_seasonal_1:
    value: 0.00022238016286435283
learning_rate_seasonal_2:
    value: 0.000648628096492995
learning_rate_seasonal_3:
    value: 0.0003579179295962485
learning_rate_trend:
    value: 0.000116284026956772
observation_period_resid:
    value: 17
observation_period_seasonal_0:
    value: 8
observation_period_seasonal_1:
    value: 18
observation_period_seasonal_2:
    value: 21
observation_period_seasonal_3:
    value: 53
observation_period_trend:
    value: 26
predict_period_num:
    value: 1
