_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 75
batch_size_seasonal_1:
    value: 58
batch_size_seasonal_2:
    value: 87
batch_size_seasonal_3:
    value: 32
batch_size_trend:
    value: 74
epochs:
    value: 300
learning_rate_resid:
    value: 0.0008213213002676373
learning_rate_seasonal_0:
    value: 0.00011521760220635876
learning_rate_seasonal_1:
    value: 0.0004694591913094869
learning_rate_seasonal_2:
    value: 0.0009536241953108215
learning_rate_seasonal_3:
    value: 7.956973552490178e-05
learning_rate_trend:
    value: 0.000462769100818871
observation_period_resid:
    value: 10
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 15
observation_period_seasonal_2:
    value: 8
observation_period_seasonal_3:
    value: 15
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
