_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 20
batch_size_seasonal_0:
    value: 20
batch_size_seasonal_1:
    value: 18
batch_size_seasonal_2:
    value: 82
batch_size_seasonal_3:
    value: 105
batch_size_trend:
    value: 22
epochs:
    value: 300
learning_rate_resid:
    value: 0.0007497827900101974
learning_rate_seasonal_0:
    value: 0.00011616369376544115
learning_rate_seasonal_1:
    value: 0.00015337174501261206
learning_rate_seasonal_2:
    value: 0.0007972264601018071
learning_rate_seasonal_3:
    value: 0.0005375314758159338
learning_rate_trend:
    value: 0.000983583342322892
observation_period_resid:
    value: 10
observation_period_seasonal_0:
    value: 23
observation_period_seasonal_1:
    value: 8
observation_period_seasonal_2:
    value: 11
observation_period_seasonal_3:
    value: 6
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
