_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 187
batch_size_seasonal_0:
    value: 23
batch_size_seasonal_1:
    value: 157
batch_size_seasonal_2:
    value: 194
batch_size_seasonal_3:
    value: 29
batch_size_trend:
    value: 217
epochs:
    value: 300
learning_rate_resid:
    value: 0.0006038465728526143
learning_rate_seasonal_0:
    value: 0.00022311137896130736
learning_rate_seasonal_1:
    value: 0.0008062079867485131
learning_rate_seasonal_2:
    value: 0.0008521571982962857
learning_rate_seasonal_3:
    value: 1.9028051396510073e-05
learning_rate_trend:
    value: 0.0005448001859417389
observation_period_resid:
    value: 21
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 15
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
