_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 132
depth:
    value: 4
dim:
    value: 128
epochs:
    value: 1
learning_rate:
    value: 0.0002161234463423553
observation_period_num:
    value: 140
predict_period_num:
    value: 1
