_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 89
batch_size_seasonal_0:
    value: 52
batch_size_seasonal_1:
    value: 133
batch_size_seasonal_2:
    value: 112
batch_size_seasonal_3:
    value: 129
batch_size_trend:
    value: 62
epochs:
    value: 300
learning_rate_resid:
    value: 0.0008694013886418433
learning_rate_seasonal_0:
    value: 0.0008850397661873524
learning_rate_seasonal_1:
    value: 0.0005780688306891082
learning_rate_seasonal_2:
    value: 0.000210758885676157
learning_rate_seasonal_3:
    value: 0.0007373980961353831
learning_rate_trend:
    value: 0.0002900878964956585
observation_period_resid:
    value: 29
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 20
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
