_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 92
batch_size_seasonal:
    value: 178
batch_size_trend:
    value: 191
epochs:
    value: 100
learning_rate_resid:
    value: 0.0008016017692160037
learning_rate_seasonal:
    value: 4.352629292904203e-05
learning_rate_trend:
    value: 2.501748654797347e-05
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
