_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 196
batch_size_seasonal_0:
    value: 137
batch_size_seasonal_1:
    value: 23
batch_size_seasonal_2:
    value: 73
batch_size_seasonal_3:
    value: 140
batch_size_trend:
    value: 52
epochs:
    value: 500
learning_rate_resid:
    value: 0.0008208326014378005
learning_rate_seasonal_0:
    value: 0.000643630558756715
learning_rate_seasonal_1:
    value: 0.0005248296748362476
learning_rate_seasonal_2:
    value: 0.0003634260125673883
learning_rate_seasonal_3:
    value: 0.0003698563143967294
learning_rate_trend:
    value: 0.0005755708306127486
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 15
observation_period_seasonal_1:
    value: 36
observation_period_seasonal_2:
    value: 25
observation_period_seasonal_3:
    value: 13
observation_period_trend:
    value: 32
predict_period_num:
    value: 1
