_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 90
batch_size_seasonal_0:
    value: 226
batch_size_seasonal_1:
    value: 147
batch_size_seasonal_2:
    value: 195
batch_size_seasonal_3:
    value: 60
batch_size_trend:
    value: 51
epochs:
    value: 300
learning_rate_resid:
    value: 5.088314251955588e-05
learning_rate_seasonal_0:
    value: 0.00010893444751318138
learning_rate_seasonal_1:
    value: 1.3398804283619012e-05
learning_rate_seasonal_2:
    value: 0.0004452983773083988
learning_rate_seasonal_3:
    value: 0.00010655426313076004
learning_rate_trend:
    value: 0.00010670057203595444
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 11
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 7
predict_period_num:
    value: 1
