_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 153
batch_size_seasonal_0:
    value: 102
batch_size_seasonal_1:
    value: 33
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 90
batch_size_trend:
    value: 56
epochs:
    value: 300
learning_rate_resid:
    value: 0.0008211719816221531
learning_rate_seasonal_0:
    value: 0.000957277784736993
learning_rate_seasonal_1:
    value: 0.00033532080877648107
learning_rate_seasonal_2:
    value: 2.0120657236148504e-05
learning_rate_seasonal_3:
    value: 0.0006481049933478129
learning_rate_trend:
    value: 0.0005582732056514692
observation_period_resid:
    value: 10
observation_period_seasonal_0:
    value: 9
observation_period_seasonal_1:
    value: 35
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
