_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 115
batch_size_seasonal_0:
    value: 227
batch_size_seasonal_1:
    value: 79
batch_size_seasonal_2:
    value: 206
batch_size_seasonal_3:
    value: 97
batch_size_trend:
    value: 233
epochs:
    value: 1
learning_rate_resid:
    value: 2.2986155697754514e-05
learning_rate_seasonal_0:
    value: 0.00010996743191969409
learning_rate_seasonal_1:
    value: 0.00011618404463534315
learning_rate_seasonal_2:
    value: 5.620223165191215e-05
learning_rate_seasonal_3:
    value: 0.00019088488065520262
learning_rate_trend:
    value: 0.0009609024079180813
observation_period_resid:
    value: 206
observation_period_seasonal_0:
    value: 205
observation_period_seasonal_1:
    value: 235
observation_period_seasonal_2:
    value: 108
observation_period_seasonal_3:
    value: 28
observation_period_trend:
    value: 9
predict_period_num:
    value: 1
