_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 95
batch_size_seasonal:
    value: 212
batch_size_trend:
    value: 164
epochs:
    value: 1000
learning_rate_resid:
    value: 0.00038404672674002805
learning_rate_seasonal:
    value: 0.00018118651407324088
learning_rate_trend:
    value: 8.866220804298829e-05
observation_period_num:
    value:
        resid: 5
        seasonal: 48
        trend: 6
predict_period_num:
    value: 1
