_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 16
batch_size_seasonal_0:
    value: 77
batch_size_seasonal_1:
    value: 17
batch_size_seasonal_2:
    value: 194
batch_size_seasonal_3:
    value: 34
batch_size_trend:
    value: 41
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004657100769993278
learning_rate_seasonal_0:
    value: 0.00026296012972942123
learning_rate_seasonal_1:
    value: 0.0009918461542730392
learning_rate_seasonal_2:
    value: 0.0009997479022770277
learning_rate_seasonal_3:
    value: 0.00012144616340285131
learning_rate_trend:
    value: 0.00013662188894747836
observation_period_resid:
    value: 18
observation_period_seasonal_0:
    value: 6
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 12
predict_period_num:
    value: 1
