_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 52
batch_size_seasonal:
    value: 245
batch_size_trend:
    value: 186
epochs:
    value: 1000
learning_rate_resid:
    value: 1.1174984505624256e-05
learning_rate_seasonal:
    value: 1.203906598183516e-05
learning_rate_trend:
    value: 4.379578565067362e-06
observation_period_num:
    value:
        resid: 5
        seasonal: 48
        trend: 6
predict_period_num:
    value: 1
