_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 19
batch_size_seasonal_0:
    value: 91
batch_size_seasonal_1:
    value: 77
batch_size_seasonal_2:
    value: 83
batch_size_seasonal_3:
    value: 177
batch_size_trend:
    value: 21
epochs:
    value: 300
learning_rate_resid:
    value: 8.012917276576874e-05
learning_rate_seasonal_0:
    value: 0.0007812705820300369
learning_rate_seasonal_1:
    value: 0.0009114576043213219
learning_rate_seasonal_2:
    value: 0.0008579355185219953
learning_rate_seasonal_3:
    value: 0.0005699121417227269
learning_rate_trend:
    value: 0.0003624766556945417
observation_period_resid:
    value: 7
observation_period_seasonal_0:
    value: 12
observation_period_seasonal_1:
    value: 7
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 6
predict_period_num:
    value: 1
