_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 196
batch_size_seasonal_0:
    value: 83
batch_size_seasonal_1:
    value: 49
batch_size_seasonal_2:
    value: 128
batch_size_seasonal_3:
    value: 120
batch_size_trend:
    value: 131
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009962477682108294
learning_rate_seasonal_0:
    value: 0.0008342583889626178
learning_rate_seasonal_1:
    value: 0.0002020917844432142
learning_rate_seasonal_2:
    value: 0.0008015640735147705
learning_rate_seasonal_3:
    value: 0.00023235087305173077
learning_rate_trend:
    value: 0.0006611942494364151
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 17
observation_period_seasonal_1:
    value: 12
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 10
observation_period_trend:
    value: 16
predict_period_num:
    value: 1
