_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 106
batch_size_seasonal_0:
    value: 198
batch_size_seasonal_1:
    value: 110
batch_size_seasonal_2:
    value: 228
batch_size_seasonal_3:
    value: 207
batch_size_trend:
    value: 40
epochs:
    value: 1
learning_rate_resid:
    value: 0.0001119409689661595
learning_rate_seasonal_0:
    value: 1.6953873681349288e-05
learning_rate_seasonal_1:
    value: 2.6674758918765654e-06
learning_rate_seasonal_2:
    value: 1.908653348807061e-06
learning_rate_seasonal_3:
    value: 3.954095822972956e-06
learning_rate_trend:
    value: 5.321087186139996e-05
observation_period_resid:
    value: 221
observation_period_seasonal_0:
    value: 102
observation_period_seasonal_1:
    value: 214
observation_period_seasonal_2:
    value: 57
observation_period_seasonal_3:
    value: 117
observation_period_trend:
    value: 166
predict_period_num:
    value: 1
