_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 62
batch_size_seasonal_0:
    value: 24
batch_size_seasonal_1:
    value: 90
batch_size_seasonal_2:
    value: 16
batch_size_seasonal_3:
    value: 29
batch_size_trend:
    value: 177
epochs:
    value: 300
learning_rate_resid:
    value: 0.00029485717567109766
learning_rate_seasonal_0:
    value: 0.0006678856212685529
learning_rate_seasonal_1:
    value: 0.00032762455811565026
learning_rate_seasonal_2:
    value: 0.00043560336174811373
learning_rate_seasonal_3:
    value: 3.211031986330471e-05
learning_rate_trend:
    value: 0.0006884572640205183
observation_period_resid:
    value: 144
observation_period_seasonal_0:
    value: 15
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 32
observation_period_seasonal_3:
    value: 8
observation_period_trend:
    value: 17
predict_period_num:
    value: 1
