_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 176
batch_size_seasonal_0:
    value: 74
batch_size_seasonal_1:
    value: 228
batch_size_seasonal_2:
    value: 47
batch_size_seasonal_3:
    value: 19
batch_size_trend:
    value: 42
epochs:
    value: 300
learning_rate_resid:
    value: 0.0002093614812893629
learning_rate_seasonal_0:
    value: 0.00013080095431673434
learning_rate_seasonal_1:
    value: 0.0002561402649349968
learning_rate_seasonal_2:
    value: 7.353708316883962e-05
learning_rate_seasonal_3:
    value: 0.0006094601430873331
learning_rate_trend:
    value: 0.0003010715173492714
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 7
observation_period_trend:
    value: 21
predict_period_num:
    value: 1
