_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 157
batch_size_seasonal_0:
    value: 84
batch_size_seasonal_1:
    value: 198
batch_size_seasonal_2:
    value: 39
batch_size_seasonal_3:
    value: 105
batch_size_trend:
    value: 42
epochs:
    value: 1
learning_rate_resid:
    value: 0.0001131828733188659
learning_rate_seasonal_0:
    value: 1.7477345198989501e-06
learning_rate_seasonal_1:
    value: 0.0009361985695843724
learning_rate_seasonal_2:
    value: 1.2510561274313113e-06
learning_rate_seasonal_3:
    value: 0.0001229063725623565
learning_rate_trend:
    value: 0.00048007972988822203
observation_period_resid:
    value: 47
observation_period_seasonal_0:
    value: 123
observation_period_seasonal_1:
    value: 34
observation_period_seasonal_2:
    value: 153
observation_period_seasonal_3:
    value: 116
observation_period_trend:
    value: 68
predict_period_num:
    value: 1
