_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 193
batch_size_seasonal_0:
    value: 35
batch_size_seasonal_1:
    value: 54
batch_size_seasonal_2:
    value: 50
batch_size_seasonal_3:
    value: 62
batch_size_trend:
    value: 79
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009206539859814936
learning_rate_seasonal_0:
    value: 0.0006987153438608318
learning_rate_seasonal_1:
    value: 0.00010269448924050796
learning_rate_seasonal_2:
    value: 0.0007513475508938876
learning_rate_seasonal_3:
    value: 0.00034981100112560135
learning_rate_trend:
    value: 0.0006447926509531084
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 18
observation_period_seasonal_1:
    value: 17
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 11
observation_period_trend:
    value: 41
predict_period_num:
    value: 1
