_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 160
batch_size_seasonal_0:
    value: 164
batch_size_seasonal_1:
    value: 41
batch_size_seasonal_2:
    value: 125
batch_size_seasonal_3:
    value: 67
batch_size_trend:
    value: 148
epochs:
    value: 300
learning_rate_resid:
    value: 9.520024519985122e-05
learning_rate_seasonal_0:
    value: 0.00048393216296688485
learning_rate_seasonal_1:
    value: 0.0001737671772475845
learning_rate_seasonal_2:
    value: 0.0009060085165079273
learning_rate_seasonal_3:
    value: 0.0005857289074754162
learning_rate_trend:
    value: 0.0009727573638935249
observation_period_resid:
    value: 10
observation_period_seasonal_0:
    value: 17
observation_period_seasonal_1:
    value: 6
observation_period_seasonal_2:
    value: 5
observation_period_seasonal_3:
    value: 14
observation_period_trend:
    value: 15
predict_period_num:
    value: 1
