_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 197
batch_size_seasonal:
    value: 166
batch_size_trend:
    value: 175
epochs:
    value: 1
learning_rate_resid:
    value: 0.0001410356282021616
learning_rate_seasonal:
    value: 0.000768124496624333
learning_rate_trend:
    value: 3.085709860334273e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
