_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 76
batch_size_seasonal_0:
    value: 256
batch_size_seasonal_1:
    value: 64
batch_size_seasonal_2:
    value: 104
batch_size_seasonal_3:
    value: 16
batch_size_trend:
    value: 55
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004139196016946088
learning_rate_seasonal_0:
    value: 0.0007598525048823074
learning_rate_seasonal_1:
    value: 0.00039336064384533397
learning_rate_seasonal_2:
    value: 0.0008824583713776
learning_rate_seasonal_3:
    value: 2.004436287423855e-05
learning_rate_trend:
    value: 0.00025142320948791635
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 5
observation_period_seasonal_1:
    value: 10
observation_period_seasonal_2:
    value: 10
observation_period_seasonal_3:
    value: 17
observation_period_trend:
    value: 15
predict_period_num:
    value: 1
