_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 69
batch_size_seasonal_0:
    value: 19
batch_size_seasonal_1:
    value: 27
batch_size_seasonal_2:
    value: 17
batch_size_seasonal_3:
    value: 48
batch_size_trend:
    value: 222
epochs:
    value: 300
learning_rate_resid:
    value: 0.0009989030292173794
learning_rate_seasonal_0:
    value: 0.00033531135729907805
learning_rate_seasonal_1:
    value: 4.162179117134796e-05
learning_rate_seasonal_2:
    value: 0.00017516285036875043
learning_rate_seasonal_3:
    value: 0.0002170887499126454
learning_rate_trend:
    value: 0.0009876273611041503
observation_period_resid:
    value: 6
observation_period_seasonal_0:
    value: 21
observation_period_seasonal_1:
    value: 19
observation_period_seasonal_2:
    value: 6
observation_period_seasonal_3:
    value: 23
observation_period_trend:
    value: 5
predict_period_num:
    value: 1
