_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 55
batch_size_seasonal_0:
    value: 172
batch_size_seasonal_1:
    value: 228
batch_size_seasonal_2:
    value: 106
batch_size_seasonal_3:
    value: 119
batch_size_trend:
    value: 85
epochs:
    value: 1
learning_rate_resid:
    value: 0.0004532689476531153
learning_rate_seasonal_0:
    value: 0.00048159122406624496
learning_rate_seasonal_1:
    value: 2.746568446689003e-05
learning_rate_seasonal_2:
    value: 0.000832907558177577
learning_rate_seasonal_3:
    value: 7.492360943561212e-05
learning_rate_trend:
    value: 1.2555052541035969e-06
observation_period_resid:
    value: 5
observation_period_seasonal_0:
    value: 120
observation_period_seasonal_1:
    value: 216
observation_period_seasonal_2:
    value: 103
observation_period_seasonal_3:
    value: 102
observation_period_trend:
    value: 154
predict_period_num:
    value: 1
