_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 35
                - 55
            "2":
                - 1
                - 35
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size_resid:
    value: 243
batch_size_seasonal:
    value: 245
batch_size_trend:
    value: 172
epochs:
    value: 100
learning_rate_resid:
    value: 6.122800877523728e-05
learning_rate_seasonal:
    value: 4.267272990148572e-05
learning_rate_trend:
    value: 3.3497132875767082e-06
observation_period_num:
    value:
        resid: 30
        seasonal: 30
        trend: 30
predict_period_num:
    value: 1
