_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size_resid:
    value: 217
batch_size_seasonal_0:
    value: 136
batch_size_seasonal_1:
    value: 16
batch_size_seasonal_2:
    value: 43
batch_size_seasonal_3:
    value: 86
batch_size_trend:
    value: 159
epochs:
    value: 300
learning_rate_resid:
    value: 0.0004243432121126998
learning_rate_seasonal_0:
    value: 0.00025484983658506644
learning_rate_seasonal_1:
    value: 4.3468440312567085e-05
learning_rate_seasonal_2:
    value: 0.00017319215956000322
learning_rate_seasonal_3:
    value: 3.488595000841005e-05
learning_rate_trend:
    value: 0.0001409470186357949
observation_period_resid:
    value: 196
observation_period_seasonal_0:
    value: 26
observation_period_seasonal_1:
    value: 5
observation_period_seasonal_2:
    value: 13
observation_period_seasonal_3:
    value: 16
observation_period_trend:
    value: 186
predict_period_num:
    value: 1
